/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.ifta.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class GetIftaVehicleReportsRequestMonth {
    public static final GetIftaVehicleReportsRequestMonth APRIL =
            new GetIftaVehicleReportsRequestMonth(Value.APRIL, "April");

    public static final GetIftaVehicleReportsRequestMonth JANUARY =
            new GetIftaVehicleReportsRequestMonth(Value.JANUARY, "January");

    public static final GetIftaVehicleReportsRequestMonth AUGUST =
            new GetIftaVehicleReportsRequestMonth(Value.AUGUST, "August");

    public static final GetIftaVehicleReportsRequestMonth JULY =
            new GetIftaVehicleReportsRequestMonth(Value.JULY, "July");

    public static final GetIftaVehicleReportsRequestMonth SEPTEMBER =
            new GetIftaVehicleReportsRequestMonth(Value.SEPTEMBER, "September");

    public static final GetIftaVehicleReportsRequestMonth OCTOBER =
            new GetIftaVehicleReportsRequestMonth(Value.OCTOBER, "October");

    public static final GetIftaVehicleReportsRequestMonth DECEMBER =
            new GetIftaVehicleReportsRequestMonth(Value.DECEMBER, "December");

    public static final GetIftaVehicleReportsRequestMonth MARCH =
            new GetIftaVehicleReportsRequestMonth(Value.MARCH, "March");

    public static final GetIftaVehicleReportsRequestMonth MAY = new GetIftaVehicleReportsRequestMonth(Value.MAY, "May");

    public static final GetIftaVehicleReportsRequestMonth JUNE =
            new GetIftaVehicleReportsRequestMonth(Value.JUNE, "June");

    public static final GetIftaVehicleReportsRequestMonth NOVEMBER =
            new GetIftaVehicleReportsRequestMonth(Value.NOVEMBER, "November");

    public static final GetIftaVehicleReportsRequestMonth FEBRUARY =
            new GetIftaVehicleReportsRequestMonth(Value.FEBRUARY, "February");

    private final Value value;

    private final String string;

    GetIftaVehicleReportsRequestMonth(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof GetIftaVehicleReportsRequestMonth
                        && this.string.equals(((GetIftaVehicleReportsRequestMonth) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case APRIL:
                return visitor.visitApril();
            case JANUARY:
                return visitor.visitJanuary();
            case AUGUST:
                return visitor.visitAugust();
            case JULY:
                return visitor.visitJuly();
            case SEPTEMBER:
                return visitor.visitSeptember();
            case OCTOBER:
                return visitor.visitOctober();
            case DECEMBER:
                return visitor.visitDecember();
            case MARCH:
                return visitor.visitMarch();
            case MAY:
                return visitor.visitMay();
            case JUNE:
                return visitor.visitJune();
            case NOVEMBER:
                return visitor.visitNovember();
            case FEBRUARY:
                return visitor.visitFebruary();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static GetIftaVehicleReportsRequestMonth valueOf(String value) {
        switch (value) {
            case "April":
                return APRIL;
            case "January":
                return JANUARY;
            case "August":
                return AUGUST;
            case "July":
                return JULY;
            case "September":
                return SEPTEMBER;
            case "October":
                return OCTOBER;
            case "December":
                return DECEMBER;
            case "March":
                return MARCH;
            case "May":
                return MAY;
            case "June":
                return JUNE;
            case "November":
                return NOVEMBER;
            case "February":
                return FEBRUARY;
            default:
                return new GetIftaVehicleReportsRequestMonth(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        JANUARY,

        FEBRUARY,

        MARCH,

        APRIL,

        MAY,

        JUNE,

        JULY,

        AUGUST,

        SEPTEMBER,

        OCTOBER,

        NOVEMBER,

        DECEMBER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitJanuary();

        T visitFebruary();

        T visitMarch();

        T visitApril();

        T visitMay();

        T visitJune();

        T visitJuly();

        T visitAugust();

        T visitSeptember();

        T visitOctober();

        T visitNovember();

        T visitDecember();

        T visitUnknown(String unknownType);
    }
}
