/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.previewapis;

import com.samsara.api.core.ClientOptions;
import com.samsara.api.core.RequestOptions;
import com.samsara.api.resources.previewapis.requests.DriversAuthTokenCreateDriverAuthTokenRequestBody;
import com.samsara.api.resources.previewapis.requests.GatewaysPairGatewaysRequestBody;
import com.samsara.api.resources.previewapis.requests.LockVehicleRequest;
import com.samsara.api.resources.previewapis.requests.UnlockVehicleRequest;
import com.samsara.api.types.DriversAuthTokenCreateDriverAuthTokenResponseBody;
import com.samsara.api.types.GatewaysPairGatewaysResponseBody;

public class PreviewApIsClient {
    protected final ClientOptions clientOptions;

    private final RawPreviewApIsClient rawClient;

    public PreviewApIsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPreviewApIsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPreviewApIsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Creates a short-lived auth token for a driver.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Driver Auth Token</strong> under the Drivers category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public DriversAuthTokenCreateDriverAuthTokenResponseBody createDriverAuthToken(
            DriversAuthTokenCreateDriverAuthTokenRequestBody request) {
        return this.rawClient.createDriverAuthToken(request).body();
    }

    /**
     * Creates a short-lived auth token for a driver.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Driver Auth Token</strong> under the Drivers category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public DriversAuthTokenCreateDriverAuthTokenResponseBody createDriverAuthToken(
            DriversAuthTokenCreateDriverAuthTokenRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.createDriverAuthToken(request, requestOptions).body();
    }

    /**
     * Lock a vehicle. This requires a vehicle gateway with locking capabilities.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void lockVehicle(String id) {
        this.rawClient.lockVehicle(id).body();
    }

    /**
     * Lock a vehicle. This requires a vehicle gateway with locking capabilities.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void lockVehicle(String id, RequestOptions requestOptions) {
        this.rawClient.lockVehicle(id, requestOptions).body();
    }

    /**
     * Lock a vehicle. This requires a vehicle gateway with locking capabilities.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void lockVehicle(String id, LockVehicleRequest request) {
        this.rawClient.lockVehicle(id, request).body();
    }

    /**
     * Lock a vehicle. This requires a vehicle gateway with locking capabilities.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void lockVehicle(String id, LockVehicleRequest request, RequestOptions requestOptions) {
        this.rawClient.lockVehicle(id, request, requestOptions).body();
    }

    /**
     * Unlock a vehicle.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void unlockVehicle(String id) {
        this.rawClient.unlockVehicle(id).body();
    }

    /**
     * Unlock a vehicle.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void unlockVehicle(String id, RequestOptions requestOptions) {
        this.rawClient.unlockVehicle(id, requestOptions).body();
    }

    /**
     * Unlock a vehicle.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void unlockVehicle(String id, UnlockVehicleRequest request) {
        this.rawClient.unlockVehicle(id, request).body();
    }

    /**
     * Unlock a vehicle.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Vehicle Lock/Unlock</strong> under the Vehicles category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public void unlockVehicle(String id, UnlockVehicleRequest request, RequestOptions requestOptions) {
        this.rawClient.unlockVehicle(id, request, requestOptions).body();
    }

    /**
     * Reassign one or more gateways to different devices in a single call. Mirrors the dashboard's &quot;Pair Gateway&quot; flow and accepts up to 50 gateway-device pairs per request. Works for any device type: vehicles, assets, equipment, trailers, industrial machines, and asset tags. By default, devices that the reassigned gateways were previously linked to remain in their current group. Pass <code>removeOrphanDevices: true</code> to move those orphaned devices to the unassigned group and clear their tags. The endpoint is currently in Preview and gated behind a feature configuration; contact your Samsara representative to enable access.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Gateways</strong> under the Setup &amp; Administration category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public GatewaysPairGatewaysResponseBody pairGateways(GatewaysPairGatewaysRequestBody request) {
        return this.rawClient.pairGateways(request).body();
    }

    /**
     * Reassign one or more gateways to different devices in a single call. Mirrors the dashboard's &quot;Pair Gateway&quot; flow and accepts up to 50 gateway-device pairs per request. Works for any device type: vehicles, assets, equipment, trailers, industrial machines, and asset tags. By default, devices that the reassigned gateways were previously linked to remain in their current group. Pass <code>removeOrphanDevices: true</code> to move those orphaned devices to the unassigned group and clear their tags. The endpoint is currently in Preview and gated behind a feature configuration; contact your Samsara representative to enable access.
     * <p><b>Rate limit:</b> 100 requests/min (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p>To use this endpoint, select <strong>Write Gateways</strong> under the Setup &amp; Administration category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     * <p>Endpoints in this section are in Preview. These APIs are not functional and are instead for soliciting feedback from our API users on the intended design of this API. Additionally, it is not guaranteed that we will be releasing an endpoint included in this section to production. This means that developers should <strong>NOT</strong> rely on these APIs to build business critical applications</p>
     * <ul>
     * <li>
     * <p>Samsara may change the structure of a preview API's interface without versioning or any notice to API users.</p>
     * </li>
     * <li>
     * <p>When an endpoint becomes generally available, it will be announced in the API <a href="https://developers.samsara.com/changelog">changelog</a>.</p>
     * </li>
     * </ul>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     */
    public GatewaysPairGatewaysResponseBody pairGateways(
            GatewaysPairGatewaysRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.pairGateways(request, requestOptions).body();
    }
}
