/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.attributes;

import com.samsara.api.core.ClientOptions;
import com.samsara.api.core.RequestOptions;
import com.samsara.api.resources.attributes.requests.CreateAttributeRequest;
import com.samsara.api.resources.attributes.requests.DeleteAttributesRequest;
import com.samsara.api.resources.attributes.requests.GetAttributeRequest;
import com.samsara.api.resources.attributes.requests.GetAttributesByEntityTypeRequest;
import com.samsara.api.resources.attributes.requests.UpdateAttributeRequest;
import com.samsara.api.types.AttributeExpandedResponse;
import com.samsara.api.types.GetAttributesByEntityTypeResponse;

public class AttributesClient {
    protected final ClientOptions clientOptions;

    private final RawAttributesClient rawClient;

    public AttributesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAttributesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAttributesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Fetch all attributes in an organization associated with either drivers or assets.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public GetAttributesByEntityTypeResponse getAttributesByEntityType(GetAttributesByEntityTypeRequest request) {
        return this.rawClient.getAttributesByEntityType(request).body();
    }

    /**
     * Fetch all attributes in an organization associated with either drivers or assets.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public GetAttributesByEntityTypeResponse getAttributesByEntityType(
            GetAttributesByEntityTypeRequest request, RequestOptions requestOptions) {
        return this.rawClient.getAttributesByEntityType(request, requestOptions).body();
    }

    /**
     * Creates a new attribute in the organization.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Write Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public AttributeExpandedResponse createAttribute(CreateAttributeRequest request) {
        return this.rawClient.createAttribute(request).body();
    }

    /**
     * Creates a new attribute in the organization.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Write Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public AttributeExpandedResponse createAttribute(CreateAttributeRequest request, RequestOptions requestOptions) {
        return this.rawClient.createAttribute(request, requestOptions).body();
    }

    /**
     * Fetch an attribute by id, including all of its applications.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public AttributeExpandedResponse getAttribute(String id, GetAttributeRequest request) {
        return this.rawClient.getAttribute(id, request).body();
    }

    /**
     * Fetch an attribute by id, including all of its applications.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public AttributeExpandedResponse getAttribute(
            String id, GetAttributeRequest request, RequestOptions requestOptions) {
        return this.rawClient.getAttribute(id, request, requestOptions).body();
    }

    /**
     * Delete an attribute by id, including all of its applications.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Write Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public String delete(String id, DeleteAttributesRequest request) {
        return this.rawClient.delete(id, request).body();
    }

    /**
     * Delete an attribute by id, including all of its applications.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Write Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public String delete(String id, DeleteAttributesRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(id, request, requestOptions).body();
    }

    /**
     * Updates an attribute in the organization.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Write Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public AttributeExpandedResponse updateAttribute(String id, UpdateAttributeRequest request) {
        return this.rawClient.updateAttribute(id, request).body();
    }

    /**
     * Updates an attribute in the organization.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Write Attributes</strong> under the Setup &amp; Administration category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public AttributeExpandedResponse updateAttribute(
            String id, UpdateAttributeRequest request, RequestOptions requestOptions) {
        return this.rawClient.updateAttribute(id, request, requestOptions).body();
    }
}
