/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.industrial.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AssetDataOutputsPatchAssetDataOutputsRequestBody.Builder.class)
public final class AssetDataOutputsPatchAssetDataOutputsRequestBody {
    private final Map<String, Object> values;

    private final Map<String, Object> additionalProperties;

    private AssetDataOutputsPatchAssetDataOutputsRequestBody(
            Map<String, Object> values, Map<String, Object> additionalProperties) {
        this.values = values;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A map of data output IDs to values. All data outputs must belong to the same asset. Only the specified IDs will be written to.
     */
    @JsonProperty("values")
    public Map<String, Object> getValues() {
        return values;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AssetDataOutputsPatchAssetDataOutputsRequestBody
                && equalTo((AssetDataOutputsPatchAssetDataOutputsRequestBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AssetDataOutputsPatchAssetDataOutputsRequestBody other) {
        return values.equals(other.values);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.values);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Map<String, Object> values = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AssetDataOutputsPatchAssetDataOutputsRequestBody other) {
            values(other.getValues());
            return this;
        }

        /**
         * <p>A map of data output IDs to values. All data outputs must belong to the same asset. Only the specified IDs will be written to.</p>
         */
        @JsonSetter(value = "values", nulls = Nulls.SKIP)
        public Builder values(Map<String, Object> values) {
            this.values.clear();
            if (values != null) {
                this.values.putAll(values);
            }
            return this;
        }

        public Builder putAllValues(Map<String, Object> values) {
            if (values != null) {
                this.values.putAll(values);
            }
            return this;
        }

        public Builder values(String key, Object value) {
            this.values.put(key, value);
            return this;
        }

        public AssetDataOutputsPatchAssetDataOutputsRequestBody build() {
            return new AssetDataOutputsPatchAssetDataOutputsRequestBody(values, additionalProperties);
        }
    }
}
