/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.equipment;

import com.samsara.api.core.ClientOptions;
import com.samsara.api.core.RequestOptions;
import com.samsara.api.resources.equipment.requests.GetEquipmentLocationsFeedRequest;
import com.samsara.api.resources.equipment.requests.GetEquipmentLocationsHistoryRequest;
import com.samsara.api.resources.equipment.requests.GetEquipmentLocationsRequest;
import com.samsara.api.resources.equipment.requests.GetEquipmentRequest;
import com.samsara.api.resources.equipment.requests.GetEquipmentStatsFeedRequest;
import com.samsara.api.resources.equipment.requests.GetEquipmentStatsHistoryRequest;
import com.samsara.api.resources.equipment.requests.GetEquipmentStatsRequest;
import com.samsara.api.resources.equipment.requests.ListEquipmentRequest;
import com.samsara.api.types.EquipmentListResponse;
import com.samsara.api.types.EquipmentLocationsListResponse;
import com.samsara.api.types.EquipmentLocationsResponse;
import com.samsara.api.types.EquipmentResponse;
import com.samsara.api.types.EquipmentStatsListResponse;
import com.samsara.api.types.EquipmentStatsResponse;

public class EquipmentClient {
    protected final ClientOptions clientOptions;

    private final RawEquipmentClient rawClient;

    public EquipmentClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawEquipmentClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawEquipmentClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of all equipment in an organization.
     */
    public EquipmentListResponse listEquipment() {
        return this.rawClient.listEquipment().body();
    }

    /**
     * Returns a list of all equipment in an organization.
     */
    public EquipmentListResponse listEquipment(RequestOptions requestOptions) {
        return this.rawClient.listEquipment(requestOptions).body();
    }

    /**
     * Returns a list of all equipment in an organization.
     */
    public EquipmentListResponse listEquipment(ListEquipmentRequest request) {
        return this.rawClient.listEquipment(request).body();
    }

    /**
     * Returns a list of all equipment in an organization.
     */
    public EquipmentListResponse listEquipment(ListEquipmentRequest request, RequestOptions requestOptions) {
        return this.rawClient.listEquipment(request, requestOptions).body();
    }

    /**
     * Returns last known locations for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsResponse getEquipmentLocations() {
        return this.rawClient.getEquipmentLocations().body();
    }

    /**
     * Returns last known locations for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsResponse getEquipmentLocations(RequestOptions requestOptions) {
        return this.rawClient.getEquipmentLocations(requestOptions).body();
    }

    /**
     * Returns last known locations for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsResponse getEquipmentLocations(GetEquipmentLocationsRequest request) {
        return this.rawClient.getEquipmentLocations(request).body();
    }

    /**
     * Returns last known locations for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsResponse getEquipmentLocations(
            GetEquipmentLocationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getEquipmentLocations(request, requestOptions).body();
    }

    /**
     * Follow a continuous feed of all equipment locations.
     * <p>Your first call to this endpoint will provide you with the most recent location for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment location updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. We'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsListResponse getEquipmentLocationsFeed() {
        return this.rawClient.getEquipmentLocationsFeed().body();
    }

    /**
     * Follow a continuous feed of all equipment locations.
     * <p>Your first call to this endpoint will provide you with the most recent location for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment location updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. We'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsListResponse getEquipmentLocationsFeed(RequestOptions requestOptions) {
        return this.rawClient.getEquipmentLocationsFeed(requestOptions).body();
    }

    /**
     * Follow a continuous feed of all equipment locations.
     * <p>Your first call to this endpoint will provide you with the most recent location for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment location updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. We'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsListResponse getEquipmentLocationsFeed(GetEquipmentLocationsFeedRequest request) {
        return this.rawClient.getEquipmentLocationsFeed(request).body();
    }

    /**
     * Follow a continuous feed of all equipment locations.
     * <p>Your first call to this endpoint will provide you with the most recent location for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment location updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. We'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsListResponse getEquipmentLocationsFeed(
            GetEquipmentLocationsFeedRequest request, RequestOptions requestOptions) {
        return this.rawClient.getEquipmentLocationsFeed(request, requestOptions).body();
    }

    /**
     * Returns historical equipment locations during the given time range. This can be optionally filtered by tags or specific equipment IDs.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsListResponse getEquipmentLocationsHistory(GetEquipmentLocationsHistoryRequest request) {
        return this.rawClient.getEquipmentLocationsHistory(request).body();
    }

    /**
     * Returns historical equipment locations during the given time range. This can be optionally filtered by tags or specific equipment IDs.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentLocationsListResponse getEquipmentLocationsHistory(
            GetEquipmentLocationsHistoryRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getEquipmentLocationsHistory(request, requestOptions)
                .body();
    }

    /**
     * Returns the last known stats for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsResponse getEquipmentStats() {
        return this.rawClient.getEquipmentStats().body();
    }

    /**
     * Returns the last known stats for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsResponse getEquipmentStats(RequestOptions requestOptions) {
        return this.rawClient.getEquipmentStats(requestOptions).body();
    }

    /**
     * Returns the last known stats for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsResponse getEquipmentStats(GetEquipmentStatsRequest request) {
        return this.rawClient.getEquipmentStats(request).body();
    }

    /**
     * Returns the last known stats for all equipment. This can be optionally filtered by tags or specific equipment IDs.
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsResponse getEquipmentStats(GetEquipmentStatsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getEquipmentStats(request, requestOptions).body();
    }

    /**
     * Follow a continuous feed of all equipment stats.
     * <p>Your first call to this endpoint will provide you with the most recent stats for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment stats updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. Each stat type has a different refresh rate, but in general we'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsListResponse getEquipmentStatsFeed() {
        return this.rawClient.getEquipmentStatsFeed().body();
    }

    /**
     * Follow a continuous feed of all equipment stats.
     * <p>Your first call to this endpoint will provide you with the most recent stats for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment stats updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. Each stat type has a different refresh rate, but in general we'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsListResponse getEquipmentStatsFeed(RequestOptions requestOptions) {
        return this.rawClient.getEquipmentStatsFeed(requestOptions).body();
    }

    /**
     * Follow a continuous feed of all equipment stats.
     * <p>Your first call to this endpoint will provide you with the most recent stats for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment stats updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. Each stat type has a different refresh rate, but in general we'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsListResponse getEquipmentStatsFeed(GetEquipmentStatsFeedRequest request) {
        return this.rawClient.getEquipmentStatsFeed(request).body();
    }

    /**
     * Follow a continuous feed of all equipment stats.
     * <p>Your first call to this endpoint will provide you with the most recent stats for each unit of equipment and a <code>pagination</code> object that contains an <code>endCursor</code>.</p>
     * <p>You can provide the <code>endCursor</code> to subsequent calls via the <code>after</code> parameter. The response will contain any equipment stats updates since that <code>endCursor</code>.</p>
     * <p>If <code>hasNextPage</code> is <code>false</code>, no updates are readily available yet. Each stat type has a different refresh rate, but in general we'd suggest waiting a minimum of 5 seconds before requesting updates.</p>
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsListResponse getEquipmentStatsFeed(
            GetEquipmentStatsFeedRequest request, RequestOptions requestOptions) {
        return this.rawClient.getEquipmentStatsFeed(request, requestOptions).body();
    }

    /**
     * Returns historical equipment status during the given time range. This can be optionally filtered by tags or specific equipment IDs.
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsListResponse getEquipmentStatsHistory(GetEquipmentStatsHistoryRequest request) {
        return this.rawClient.getEquipmentStatsHistory(request).body();
    }

    /**
     * Returns historical equipment status during the given time range. This can be optionally filtered by tags or specific equipment IDs.
     * <p><b>Rate limit:</b> 150 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment Statistics</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentStatsListResponse getEquipmentStatsHistory(
            GetEquipmentStatsHistoryRequest request, RequestOptions requestOptions) {
        return this.rawClient.getEquipmentStatsHistory(request, requestOptions).body();
    }

    /**
     * Retrieves the unit of equipment with the given Samsara ID.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentResponse getEquipment(String id) {
        return this.rawClient.getEquipment(id).body();
    }

    /**
     * Retrieves the unit of equipment with the given Samsara ID.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentResponse getEquipment(String id, RequestOptions requestOptions) {
        return this.rawClient.getEquipment(id, requestOptions).body();
    }

    /**
     * Retrieves the unit of equipment with the given Samsara ID.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentResponse getEquipment(String id, GetEquipmentRequest request) {
        return this.rawClient.getEquipment(id, request).body();
    }

    /**
     * Retrieves the unit of equipment with the given Samsara ID.
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Equipment</strong> under the Equipment category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a></p>
     */
    public EquipmentResponse getEquipment(String id, GetEquipmentRequest request, RequestOptions requestOptions) {
        return this.rawClient.getEquipment(id, request, requestOptions).body();
    }
}
