/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AssetsInputsResponseResponseBody.Builder.class)
public final class AssetsInputsResponseResponseBody {
    private final AssetsInputsAssetResponseResponseBody asset;

    private final Optional<AssetsInputsAuxInputResponseBody> auxInput;

    private final String happenedAtTime;

    private final AssetsInputsResponseResponseBodyUnits units;

    private final String value;

    private final Map<String, Object> additionalProperties;

    private AssetsInputsResponseResponseBody(
            AssetsInputsAssetResponseResponseBody asset,
            Optional<AssetsInputsAuxInputResponseBody> auxInput,
            String happenedAtTime,
            AssetsInputsResponseResponseBodyUnits units,
            String value,
            Map<String, Object> additionalProperties) {
        this.asset = asset;
        this.auxInput = auxInput;
        this.happenedAtTime = happenedAtTime;
        this.units = units;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("asset")
    public AssetsInputsAssetResponseResponseBody getAsset() {
        return asset;
    }

    @JsonProperty("auxInput")
    public Optional<AssetsInputsAuxInputResponseBody> getAuxInput() {
        return auxInput;
    }

    /**
     * @return UTC timestamp in RFC 3339 format of the event.
     */
    @JsonProperty("happenedAtTime")
    public String getHappenedAtTime() {
        return happenedAtTime;
    }

    /**
     * @return Units of the values in the returned data.  Valid values: <code>boolean</code>, <code>millivolts</code>, <code>microamps</code>
     */
    @JsonProperty("units")
    public AssetsInputsResponseResponseBodyUnits getUnits() {
        return units;
    }

    /**
     * @return Value of the data point.
     */
    @JsonProperty("value")
    public String getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AssetsInputsResponseResponseBody && equalTo((AssetsInputsResponseResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AssetsInputsResponseResponseBody other) {
        return asset.equals(other.asset)
                && auxInput.equals(other.auxInput)
                && happenedAtTime.equals(other.happenedAtTime)
                && units.equals(other.units)
                && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.asset, this.auxInput, this.happenedAtTime, this.units, this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AssetStage builder() {
        return new Builder();
    }

    public interface AssetStage {
        HappenedAtTimeStage asset(@NotNull AssetsInputsAssetResponseResponseBody asset);

        Builder from(AssetsInputsResponseResponseBody other);
    }

    public interface HappenedAtTimeStage {
        /**
         * <p>UTC timestamp in RFC 3339 format of the event.</p>
         */
        UnitsStage happenedAtTime(@NotNull String happenedAtTime);
    }

    public interface UnitsStage {
        /**
         * <p>Units of the values in the returned data.  Valid values: <code>boolean</code>, <code>millivolts</code>, <code>microamps</code></p>
         */
        ValueStage units(@NotNull AssetsInputsResponseResponseBodyUnits units);
    }

    public interface ValueStage {
        /**
         * <p>Value of the data point.</p>
         */
        _FinalStage value(@NotNull String value);
    }

    public interface _FinalStage {
        AssetsInputsResponseResponseBody build();

        _FinalStage auxInput(Optional<AssetsInputsAuxInputResponseBody> auxInput);

        _FinalStage auxInput(AssetsInputsAuxInputResponseBody auxInput);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AssetStage, HappenedAtTimeStage, UnitsStage, ValueStage, _FinalStage {
        private AssetsInputsAssetResponseResponseBody asset;

        private String happenedAtTime;

        private AssetsInputsResponseResponseBodyUnits units;

        private String value;

        private Optional<AssetsInputsAuxInputResponseBody> auxInput = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AssetsInputsResponseResponseBody other) {
            asset(other.getAsset());
            auxInput(other.getAuxInput());
            happenedAtTime(other.getHappenedAtTime());
            units(other.getUnits());
            value(other.getValue());
            return this;
        }

        @java.lang.Override
        @JsonSetter("asset")
        public HappenedAtTimeStage asset(@NotNull AssetsInputsAssetResponseResponseBody asset) {
            this.asset = Objects.requireNonNull(asset, "asset must not be null");
            return this;
        }

        /**
         * <p>UTC timestamp in RFC 3339 format of the event.</p>
         * <p>UTC timestamp in RFC 3339 format of the event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("happenedAtTime")
        public UnitsStage happenedAtTime(@NotNull String happenedAtTime) {
            this.happenedAtTime = Objects.requireNonNull(happenedAtTime, "happenedAtTime must not be null");
            return this;
        }

        /**
         * <p>Units of the values in the returned data.  Valid values: <code>boolean</code>, <code>millivolts</code>, <code>microamps</code></p>
         * <p>Units of the values in the returned data.  Valid values: <code>boolean</code>, <code>millivolts</code>, <code>microamps</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("units")
        public ValueStage units(@NotNull AssetsInputsResponseResponseBodyUnits units) {
            this.units = Objects.requireNonNull(units, "units must not be null");
            return this;
        }

        /**
         * <p>Value of the data point.</p>
         * <p>Value of the data point.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("value")
        public _FinalStage value(@NotNull String value) {
            this.value = Objects.requireNonNull(value, "value must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage auxInput(AssetsInputsAuxInputResponseBody auxInput) {
            this.auxInput = Optional.ofNullable(auxInput);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "auxInput", nulls = Nulls.SKIP)
        public _FinalStage auxInput(Optional<AssetsInputsAuxInputResponseBody> auxInput) {
            this.auxInput = auxInput;
            return this;
        }

        @java.lang.Override
        public AssetsInputsResponseResponseBody build() {
            return new AssetsInputsResponseResponseBody(
                    asset, auxInput, happenedAtTime, units, value, additionalProperties);
        }
    }
}
