/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BehaviorResponseBodyCoachableBehaviorType {
    public static final BehaviorResponseBodyCoachableBehaviorType ACCELERATION =
            new BehaviorResponseBodyCoachableBehaviorType(Value.ACCELERATION, "acceleration");

    public static final BehaviorResponseBodyCoachableBehaviorType BRAKING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.BRAKING, "braking");

    public static final BehaviorResponseBodyCoachableBehaviorType FORWARD_COLLISION_WARNING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.FORWARD_COLLISION_WARNING, "forwardCollisionWarning");

    public static final BehaviorResponseBodyCoachableBehaviorType LATE_RESPONSE =
            new BehaviorResponseBodyCoachableBehaviorType(Value.LATE_RESPONSE, "lateResponse");

    public static final BehaviorResponseBodyCoachableBehaviorType ROLLOVER_PROTECTION_BRAKE_CONTROL_ACTIVATED =
            new BehaviorResponseBodyCoachableBehaviorType(
                    Value.ROLLOVER_PROTECTION_BRAKE_CONTROL_ACTIVATED, "rolloverProtectionBrakeControlActivated");

    public static final BehaviorResponseBodyCoachableBehaviorType LANE_DEPARTURE =
            new BehaviorResponseBodyCoachableBehaviorType(Value.LANE_DEPARTURE, "laneDeparture");

    public static final BehaviorResponseBodyCoachableBehaviorType SMOKING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.SMOKING, "smoking");

    public static final BehaviorResponseBodyCoachableBehaviorType MAX_SPEED =
            new BehaviorResponseBodyCoachableBehaviorType(Value.MAX_SPEED, "maxSpeed");

    public static final BehaviorResponseBodyCoachableBehaviorType UNKNOWN =
            new BehaviorResponseBodyCoachableBehaviorType(Value.UNKNOWN, "unknown");

    public static final BehaviorResponseBodyCoachableBehaviorType FALSE_POSITIVE =
            new BehaviorResponseBodyCoachableBehaviorType(Value.FALSE_POSITIVE, "falsePositive");

    public static final BehaviorResponseBodyCoachableBehaviorType SPEEDING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.SPEEDING, "speeding");

    public static final BehaviorResponseBodyCoachableBehaviorType MOBILE_USAGE =
            new BehaviorResponseBodyCoachableBehaviorType(Value.MOBILE_USAGE, "mobileUsage");

    public static final BehaviorResponseBodyCoachableBehaviorType ROLLING_STOP =
            new BehaviorResponseBodyCoachableBehaviorType(Value.ROLLING_STOP, "rollingStop");

    public static final BehaviorResponseBodyCoachableBehaviorType TAILGATING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.TAILGATING, "tailgating");

    public static final BehaviorResponseBodyCoachableBehaviorType DEFENSIVE_DRIVING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.DEFENSIVE_DRIVING, "defensiveDriving");

    public static final BehaviorResponseBodyCoachableBehaviorType EATING_DRINKING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.EATING_DRINKING, "eatingDrinking");

    public static final BehaviorResponseBodyCoachableBehaviorType NO_SEATBELT =
            new BehaviorResponseBodyCoachableBehaviorType(Value.NO_SEATBELT, "noSeatbelt");

    public static final BehaviorResponseBodyCoachableBehaviorType CRASH =
            new BehaviorResponseBodyCoachableBehaviorType(Value.CRASH, "crash");

    public static final BehaviorResponseBodyCoachableBehaviorType EVENT =
            new BehaviorResponseBodyCoachableBehaviorType(Value.EVENT, "event");

    public static final BehaviorResponseBodyCoachableBehaviorType ROLLOVER =
            new BehaviorResponseBodyCoachableBehaviorType(Value.ROLLOVER, "rollover");

    public static final BehaviorResponseBodyCoachableBehaviorType DRINK_POLICY =
            new BehaviorResponseBodyCoachableBehaviorType(Value.DRINK_POLICY, "drinkPolicy");

    public static final BehaviorResponseBodyCoachableBehaviorType OBSTRUCTED_CAMERA =
            new BehaviorResponseBodyCoachableBehaviorType(Value.OBSTRUCTED_CAMERA, "obstructedCamera");

    public static final BehaviorResponseBodyCoachableBehaviorType HOS_VIOLATION =
            new BehaviorResponseBodyCoachableBehaviorType(Value.HOS_VIOLATION, "hosViolation");

    public static final BehaviorResponseBodyCoachableBehaviorType IDLING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.IDLING, "idling");

    public static final BehaviorResponseBodyCoachableBehaviorType YAW_CONTROL_BRAKE_CONTROL_ACTIVATED =
            new BehaviorResponseBodyCoachableBehaviorType(
                    Value.YAW_CONTROL_BRAKE_CONTROL_ACTIVATED, "yawControlBrakeControlActivated");

    public static final BehaviorResponseBodyCoachableBehaviorType SEVERE_SPEEDING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.SEVERE_SPEEDING, "severeSpeeding");

    public static final BehaviorResponseBodyCoachableBehaviorType FOOD_POLICY =
            new BehaviorResponseBodyCoachableBehaviorType(Value.FOOD_POLICY, "foodPolicy");

    public static final BehaviorResponseBodyCoachableBehaviorType ROLLOVER_PROTECTION =
            new BehaviorResponseBodyCoachableBehaviorType(Value.ROLLOVER_PROTECTION, "rolloverProtection");

    public static final BehaviorResponseBodyCoachableBehaviorType YAW_CONTROL =
            new BehaviorResponseBodyCoachableBehaviorType(Value.YAW_CONTROL, "yawControl");

    public static final BehaviorResponseBodyCoachableBehaviorType MASK_POLICY =
            new BehaviorResponseBodyCoachableBehaviorType(Value.MASK_POLICY, "maskPolicy");

    public static final BehaviorResponseBodyCoachableBehaviorType GENERIC_DISTRACTION =
            new BehaviorResponseBodyCoachableBehaviorType(Value.GENERIC_DISTRACTION, "genericDistraction");

    public static final BehaviorResponseBodyCoachableBehaviorType ROLLOVER_PROTECTION_ENGINE_CONTROL_ACTIVATED =
            new BehaviorResponseBodyCoachableBehaviorType(
                    Value.ROLLOVER_PROTECTION_ENGINE_CONTROL_ACTIVATED, "rolloverProtectionEngineControlActivated");

    public static final BehaviorResponseBodyCoachableBehaviorType NEAR_COLLISON =
            new BehaviorResponseBodyCoachableBehaviorType(Value.NEAR_COLLISON, "nearCollison");

    public static final BehaviorResponseBodyCoachableBehaviorType CAMERA_OBSTRUCTION =
            new BehaviorResponseBodyCoachableBehaviorType(Value.CAMERA_OBSTRUCTION, "cameraObstruction");

    public static final BehaviorResponseBodyCoachableBehaviorType ROLLING_RAILROAD_CROSSING =
            new BehaviorResponseBodyCoachableBehaviorType(Value.ROLLING_RAILROAD_CROSSING, "rollingRailroadCrossing");

    public static final BehaviorResponseBodyCoachableBehaviorType DROWSY =
            new BehaviorResponseBodyCoachableBehaviorType(Value.DROWSY, "drowsy");

    public static final BehaviorResponseBodyCoachableBehaviorType PASSENGER_POLICY =
            new BehaviorResponseBodyCoachableBehaviorType(Value.PASSENGER_POLICY, "passengerPolicy");

    public static final BehaviorResponseBodyCoachableBehaviorType OUTWARD_OBSTRUCTION =
            new BehaviorResponseBodyCoachableBehaviorType(Value.OUTWARD_OBSTRUCTION, "outwardObstruction");

    public static final BehaviorResponseBodyCoachableBehaviorType RAN_RED_LIGHT =
            new BehaviorResponseBodyCoachableBehaviorType(Value.RAN_RED_LIGHT, "ranRedLight");

    public static final BehaviorResponseBodyCoachableBehaviorType DID_NOT_YIELD =
            new BehaviorResponseBodyCoachableBehaviorType(Value.DID_NOT_YIELD, "didNotYield");

    public static final BehaviorResponseBodyCoachableBehaviorType YAW_CONTROL_ENGINE_CONTROL_ACTIVATED =
            new BehaviorResponseBodyCoachableBehaviorType(
                    Value.YAW_CONTROL_ENGINE_CONTROL_ACTIVATED, "yawControlEngineControlActivated");

    public static final BehaviorResponseBodyCoachableBehaviorType HARSH_TURN =
            new BehaviorResponseBodyCoachableBehaviorType(Value.HARSH_TURN, "harshTurn");

    private final Value value;

    private final String string;

    BehaviorResponseBodyCoachableBehaviorType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BehaviorResponseBodyCoachableBehaviorType
                        && this.string.equals(((BehaviorResponseBodyCoachableBehaviorType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ACCELERATION:
                return visitor.visitAcceleration();
            case BRAKING:
                return visitor.visitBraking();
            case FORWARD_COLLISION_WARNING:
                return visitor.visitForwardCollisionWarning();
            case LATE_RESPONSE:
                return visitor.visitLateResponse();
            case ROLLOVER_PROTECTION_BRAKE_CONTROL_ACTIVATED:
                return visitor.visitRolloverProtectionBrakeControlActivated();
            case LANE_DEPARTURE:
                return visitor.visitLaneDeparture();
            case SMOKING:
                return visitor.visitSmoking();
            case MAX_SPEED:
                return visitor.visitMaxSpeed();
            case UNKNOWN:
                return visitor.visitUnknown();
            case FALSE_POSITIVE:
                return visitor.visitFalsePositive();
            case SPEEDING:
                return visitor.visitSpeeding();
            case MOBILE_USAGE:
                return visitor.visitMobileUsage();
            case ROLLING_STOP:
                return visitor.visitRollingStop();
            case TAILGATING:
                return visitor.visitTailgating();
            case DEFENSIVE_DRIVING:
                return visitor.visitDefensiveDriving();
            case EATING_DRINKING:
                return visitor.visitEatingDrinking();
            case NO_SEATBELT:
                return visitor.visitNoSeatbelt();
            case CRASH:
                return visitor.visitCrash();
            case EVENT:
                return visitor.visitEvent();
            case ROLLOVER:
                return visitor.visitRollover();
            case DRINK_POLICY:
                return visitor.visitDrinkPolicy();
            case OBSTRUCTED_CAMERA:
                return visitor.visitObstructedCamera();
            case HOS_VIOLATION:
                return visitor.visitHosViolation();
            case IDLING:
                return visitor.visitIdling();
            case YAW_CONTROL_BRAKE_CONTROL_ACTIVATED:
                return visitor.visitYawControlBrakeControlActivated();
            case SEVERE_SPEEDING:
                return visitor.visitSevereSpeeding();
            case FOOD_POLICY:
                return visitor.visitFoodPolicy();
            case ROLLOVER_PROTECTION:
                return visitor.visitRolloverProtection();
            case YAW_CONTROL:
                return visitor.visitYawControl();
            case MASK_POLICY:
                return visitor.visitMaskPolicy();
            case GENERIC_DISTRACTION:
                return visitor.visitGenericDistraction();
            case ROLLOVER_PROTECTION_ENGINE_CONTROL_ACTIVATED:
                return visitor.visitRolloverProtectionEngineControlActivated();
            case NEAR_COLLISON:
                return visitor.visitNearCollison();
            case CAMERA_OBSTRUCTION:
                return visitor.visitCameraObstruction();
            case ROLLING_RAILROAD_CROSSING:
                return visitor.visitRollingRailroadCrossing();
            case DROWSY:
                return visitor.visitDrowsy();
            case PASSENGER_POLICY:
                return visitor.visitPassengerPolicy();
            case OUTWARD_OBSTRUCTION:
                return visitor.visitOutwardObstruction();
            case RAN_RED_LIGHT:
                return visitor.visitRanRedLight();
            case DID_NOT_YIELD:
                return visitor.visitDidNotYield();
            case YAW_CONTROL_ENGINE_CONTROL_ACTIVATED:
                return visitor.visitYawControlEngineControlActivated();
            case HARSH_TURN:
                return visitor.visitHarshTurn();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BehaviorResponseBodyCoachableBehaviorType valueOf(String value) {
        switch (value) {
            case "acceleration":
                return ACCELERATION;
            case "braking":
                return BRAKING;
            case "forwardCollisionWarning":
                return FORWARD_COLLISION_WARNING;
            case "lateResponse":
                return LATE_RESPONSE;
            case "rolloverProtectionBrakeControlActivated":
                return ROLLOVER_PROTECTION_BRAKE_CONTROL_ACTIVATED;
            case "laneDeparture":
                return LANE_DEPARTURE;
            case "smoking":
                return SMOKING;
            case "maxSpeed":
                return MAX_SPEED;
            case "unknown":
                return UNKNOWN;
            case "falsePositive":
                return FALSE_POSITIVE;
            case "speeding":
                return SPEEDING;
            case "mobileUsage":
                return MOBILE_USAGE;
            case "rollingStop":
                return ROLLING_STOP;
            case "tailgating":
                return TAILGATING;
            case "defensiveDriving":
                return DEFENSIVE_DRIVING;
            case "eatingDrinking":
                return EATING_DRINKING;
            case "noSeatbelt":
                return NO_SEATBELT;
            case "crash":
                return CRASH;
            case "event":
                return EVENT;
            case "rollover":
                return ROLLOVER;
            case "drinkPolicy":
                return DRINK_POLICY;
            case "obstructedCamera":
                return OBSTRUCTED_CAMERA;
            case "hosViolation":
                return HOS_VIOLATION;
            case "idling":
                return IDLING;
            case "yawControlBrakeControlActivated":
                return YAW_CONTROL_BRAKE_CONTROL_ACTIVATED;
            case "severeSpeeding":
                return SEVERE_SPEEDING;
            case "foodPolicy":
                return FOOD_POLICY;
            case "rolloverProtection":
                return ROLLOVER_PROTECTION;
            case "yawControl":
                return YAW_CONTROL;
            case "maskPolicy":
                return MASK_POLICY;
            case "genericDistraction":
                return GENERIC_DISTRACTION;
            case "rolloverProtectionEngineControlActivated":
                return ROLLOVER_PROTECTION_ENGINE_CONTROL_ACTIVATED;
            case "nearCollison":
                return NEAR_COLLISON;
            case "cameraObstruction":
                return CAMERA_OBSTRUCTION;
            case "rollingRailroadCrossing":
                return ROLLING_RAILROAD_CROSSING;
            case "drowsy":
                return DROWSY;
            case "passengerPolicy":
                return PASSENGER_POLICY;
            case "outwardObstruction":
                return OUTWARD_OBSTRUCTION;
            case "ranRedLight":
                return RAN_RED_LIGHT;
            case "didNotYield":
                return DID_NOT_YIELD;
            case "yawControlEngineControlActivated":
                return YAW_CONTROL_ENGINE_CONTROL_ACTIVATED;
            case "harshTurn":
                return HARSH_TURN;
            default:
                return new BehaviorResponseBodyCoachableBehaviorType(Value._UNKNOWN, value);
        }
    }

    public enum Value {
        ACCELERATION,

        BRAKING,

        CAMERA_OBSTRUCTION,

        CRASH,

        DEFENSIVE_DRIVING,

        DID_NOT_YIELD,

        DRINK_POLICY,

        DROWSY,

        EATING_DRINKING,

        EVENT,

        FALSE_POSITIVE,

        FOOD_POLICY,

        FORWARD_COLLISION_WARNING,

        GENERIC_DISTRACTION,

        HARSH_TURN,

        HOS_VIOLATION,

        IDLING,

        LANE_DEPARTURE,

        LATE_RESPONSE,

        MASK_POLICY,

        MAX_SPEED,

        MOBILE_USAGE,

        NEAR_COLLISON,

        NO_SEATBELT,

        OBSTRUCTED_CAMERA,

        OUTWARD_OBSTRUCTION,

        PASSENGER_POLICY,

        RAN_RED_LIGHT,

        ROLLING_RAILROAD_CROSSING,

        ROLLING_STOP,

        ROLLOVER,

        ROLLOVER_PROTECTION,

        ROLLOVER_PROTECTION_BRAKE_CONTROL_ACTIVATED,

        ROLLOVER_PROTECTION_ENGINE_CONTROL_ACTIVATED,

        SEVERE_SPEEDING,

        SMOKING,

        SPEEDING,

        TAILGATING,

        UNKNOWN,

        YAW_CONTROL,

        YAW_CONTROL_BRAKE_CONTROL_ACTIVATED,

        YAW_CONTROL_ENGINE_CONTROL_ACTIVATED,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitAcceleration();

        T visitBraking();

        T visitCameraObstruction();

        T visitCrash();

        T visitDefensiveDriving();

        T visitDidNotYield();

        T visitDrinkPolicy();

        T visitDrowsy();

        T visitEatingDrinking();

        T visitEvent();

        T visitFalsePositive();

        T visitFoodPolicy();

        T visitForwardCollisionWarning();

        T visitGenericDistraction();

        T visitHarshTurn();

        T visitHosViolation();

        T visitIdling();

        T visitLaneDeparture();

        T visitLateResponse();

        T visitMaskPolicy();

        T visitMaxSpeed();

        T visitMobileUsage();

        T visitNearCollison();

        T visitNoSeatbelt();

        T visitObstructedCamera();

        T visitOutwardObstruction();

        T visitPassengerPolicy();

        T visitRanRedLight();

        T visitRollingRailroadCrossing();

        T visitRollingStop();

        T visitRollover();

        T visitRolloverProtection();

        T visitRolloverProtectionBrakeControlActivated();

        T visitRolloverProtectionEngineControlActivated();

        T visitSevereSpeeding();

        T visitSmoking();

        T visitSpeeding();

        T visitTailgating();

        T visitUnknown();

        T visitYawControl();

        T visitYawControlBrakeControlActivated();

        T visitYawControlEngineControlActivated();

        T visitUnknown(String unknownType);
    }
}
