/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DriverEldRulesetCycle {
    public static final DriverEldRulesetCycle WI80HOUR8DAY =
            new DriverEldRulesetCycle(Value.WI80HOUR8DAY, "WI 80 hour / 8 day");

    public static final DriverEldRulesetCycle OK60HOUR7DAY =
            new DriverEldRulesetCycle(Value.OK60HOUR7DAY, "OK 60 hour / 7 day");

    public static final DriverEldRulesetCycle OR80HOUR8DAY =
            new DriverEldRulesetCycle(Value.OR80HOUR8DAY, "OR 80 hour / 8 day");

    public static final DriverEldRulesetCycle CA80HOUR8DAY =
            new DriverEldRulesetCycle(Value.CA80HOUR8DAY, "CA 80 hour / 8 day");

    public static final DriverEldRulesetCycle NE70HOUR7DAY =
            new DriverEldRulesetCycle(Value.NE70HOUR7DAY, "NE 70 hour / 7 day");

    public static final DriverEldRulesetCycle SC80HOUR8DAY =
            new DriverEldRulesetCycle(Value.SC80HOUR8DAY, "SC 80 hour / 8 day");

    public static final DriverEldRulesetCycle AK70HOUR7DAY =
            new DriverEldRulesetCycle(Value.AK70HOUR7DAY, "AK 70 hour / 7 day");

    public static final DriverEldRulesetCycle NC80HOUR8DAY =
            new DriverEldRulesetCycle(Value.NC80HOUR8DAY, "NC 80 hour / 8 day");

    public static final DriverEldRulesetCycle FL80HOUR8DAY =
            new DriverEldRulesetCycle(Value.FL80HOUR8DAY, "FL 80 hour / 8 day");

    public static final DriverEldRulesetCycle NC70HOUR7DAY =
            new DriverEldRulesetCycle(Value.NC70HOUR7DAY, "NC 70 hour / 7 day");

    public static final DriverEldRulesetCycle FL70HOUR7DAY =
            new DriverEldRulesetCycle(Value.FL70HOUR7DAY, "FL 70 hour / 7 day");

    public static final DriverEldRulesetCycle USA70HOUR8DAY =
            new DriverEldRulesetCycle(Value.USA70HOUR8DAY, "USA 70 hour / 8 day");

    public static final DriverEldRulesetCycle CANADA_SOUTH_CYCLE2120HOUR14DAY = new DriverEldRulesetCycle(
            Value.CANADA_SOUTH_CYCLE2120HOUR14DAY, "Canada South Cycle 2 (120 hour / 14 day)");

    public static final DriverEldRulesetCycle WI70HOUR7DAY =
            new DriverEldRulesetCycle(Value.WI70HOUR7DAY, "WI 70 hour / 7 day");

    public static final DriverEldRulesetCycle CANADA_NORTH_CYCLE2120HOUR14DAY = new DriverEldRulesetCycle(
            Value.CANADA_NORTH_CYCLE2120HOUR14DAY, "Canada North Cycle 2 (120 hour / 14 day)");

    public static final DriverEldRulesetCycle OR70HOUR7DAY =
            new DriverEldRulesetCycle(Value.OR70HOUR7DAY, "OR 70 hour / 7 day");

    public static final DriverEldRulesetCycle CANADA_SOUTH_CYCLE170HOUR7DAY =
            new DriverEldRulesetCycle(Value.CANADA_SOUTH_CYCLE170HOUR7DAY, "Canada South Cycle 1 (70 hour / 7 day)");

    public static final DriverEldRulesetCycle AK80HOUR8DAY =
            new DriverEldRulesetCycle(Value.AK80HOUR8DAY, "AK 80 hour / 8 day");

    public static final DriverEldRulesetCycle USA60HOUR7DAY =
            new DriverEldRulesetCycle(Value.USA60HOUR7DAY, "USA 60 hour / 7 day");

    public static final DriverEldRulesetCycle TX70HOUR7DAY =
            new DriverEldRulesetCycle(Value.TX70HOUR7DAY, "TX 70 hour / 7 day");

    public static final DriverEldRulesetCycle CANADA_NORTH_CYCLE180HOUR7DAY =
            new DriverEldRulesetCycle(Value.CANADA_NORTH_CYCLE180HOUR7DAY, "Canada North Cycle 1 (80 hour / 7 day)");

    public static final DriverEldRulesetCycle SC70HOUR7DAY =
            new DriverEldRulesetCycle(Value.SC70HOUR7DAY, "SC 70 hour / 7 day");

    public static final DriverEldRulesetCycle OK70HOUR8DAY =
            new DriverEldRulesetCycle(Value.OK70HOUR8DAY, "OK 70 hour / 8 day");

    public static final DriverEldRulesetCycle NE80HOUR8DAY =
            new DriverEldRulesetCycle(Value.NE80HOUR8DAY, "NE 80 hour / 8 day");

    public static final DriverEldRulesetCycle CA112HOUR8DAY =
            new DriverEldRulesetCycle(Value.CA112HOUR8DAY, "CA 112 hour / 8 day");

    private final Value value;

    private final String string;

    DriverEldRulesetCycle(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DriverEldRulesetCycle
                        && this.string.equals(((DriverEldRulesetCycle) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WI80HOUR8DAY:
                return visitor.visitWi80Hour8Day();
            case OK60HOUR7DAY:
                return visitor.visitOk60Hour7Day();
            case OR80HOUR8DAY:
                return visitor.visitOr80Hour8Day();
            case CA80HOUR8DAY:
                return visitor.visitCa80Hour8Day();
            case NE70HOUR7DAY:
                return visitor.visitNe70Hour7Day();
            case SC80HOUR8DAY:
                return visitor.visitSc80Hour8Day();
            case AK70HOUR7DAY:
                return visitor.visitAk70Hour7Day();
            case NC80HOUR8DAY:
                return visitor.visitNc80Hour8Day();
            case FL80HOUR8DAY:
                return visitor.visitFl80Hour8Day();
            case NC70HOUR7DAY:
                return visitor.visitNc70Hour7Day();
            case FL70HOUR7DAY:
                return visitor.visitFl70Hour7Day();
            case USA70HOUR8DAY:
                return visitor.visitUsa70Hour8Day();
            case CANADA_SOUTH_CYCLE2120HOUR14DAY:
                return visitor.visitCanadaSouthCycle2120Hour14Day();
            case WI70HOUR7DAY:
                return visitor.visitWi70Hour7Day();
            case CANADA_NORTH_CYCLE2120HOUR14DAY:
                return visitor.visitCanadaNorthCycle2120Hour14Day();
            case OR70HOUR7DAY:
                return visitor.visitOr70Hour7Day();
            case CANADA_SOUTH_CYCLE170HOUR7DAY:
                return visitor.visitCanadaSouthCycle170Hour7Day();
            case AK80HOUR8DAY:
                return visitor.visitAk80Hour8Day();
            case USA60HOUR7DAY:
                return visitor.visitUsa60Hour7Day();
            case TX70HOUR7DAY:
                return visitor.visitTx70Hour7Day();
            case CANADA_NORTH_CYCLE180HOUR7DAY:
                return visitor.visitCanadaNorthCycle180Hour7Day();
            case SC70HOUR7DAY:
                return visitor.visitSc70Hour7Day();
            case OK70HOUR8DAY:
                return visitor.visitOk70Hour8Day();
            case NE80HOUR8DAY:
                return visitor.visitNe80Hour8Day();
            case CA112HOUR8DAY:
                return visitor.visitCa112Hour8Day();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DriverEldRulesetCycle valueOf(String value) {
        switch (value) {
            case "WI 80 hour / 8 day":
                return WI80HOUR8DAY;
            case "OK 60 hour / 7 day":
                return OK60HOUR7DAY;
            case "OR 80 hour / 8 day":
                return OR80HOUR8DAY;
            case "CA 80 hour / 8 day":
                return CA80HOUR8DAY;
            case "NE 70 hour / 7 day":
                return NE70HOUR7DAY;
            case "SC 80 hour / 8 day":
                return SC80HOUR8DAY;
            case "AK 70 hour / 7 day":
                return AK70HOUR7DAY;
            case "NC 80 hour / 8 day":
                return NC80HOUR8DAY;
            case "FL 80 hour / 8 day":
                return FL80HOUR8DAY;
            case "NC 70 hour / 7 day":
                return NC70HOUR7DAY;
            case "FL 70 hour / 7 day":
                return FL70HOUR7DAY;
            case "USA 70 hour / 8 day":
                return USA70HOUR8DAY;
            case "Canada South Cycle 2 (120 hour / 14 day)":
                return CANADA_SOUTH_CYCLE2120HOUR14DAY;
            case "WI 70 hour / 7 day":
                return WI70HOUR7DAY;
            case "Canada North Cycle 2 (120 hour / 14 day)":
                return CANADA_NORTH_CYCLE2120HOUR14DAY;
            case "OR 70 hour / 7 day":
                return OR70HOUR7DAY;
            case "Canada South Cycle 1 (70 hour / 7 day)":
                return CANADA_SOUTH_CYCLE170HOUR7DAY;
            case "AK 80 hour / 8 day":
                return AK80HOUR8DAY;
            case "USA 60 hour / 7 day":
                return USA60HOUR7DAY;
            case "TX 70 hour / 7 day":
                return TX70HOUR7DAY;
            case "Canada North Cycle 1 (80 hour / 7 day)":
                return CANADA_NORTH_CYCLE180HOUR7DAY;
            case "SC 70 hour / 7 day":
                return SC70HOUR7DAY;
            case "OK 70 hour / 8 day":
                return OK70HOUR8DAY;
            case "NE 80 hour / 8 day":
                return NE80HOUR8DAY;
            case "CA 112 hour / 8 day":
                return CA112HOUR8DAY;
            default:
                return new DriverEldRulesetCycle(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        USA60HOUR7DAY,

        USA70HOUR8DAY,

        AK80HOUR8DAY,

        AK70HOUR7DAY,

        CA80HOUR8DAY,

        CA112HOUR8DAY,

        FL80HOUR8DAY,

        FL70HOUR7DAY,

        NE80HOUR8DAY,

        NE70HOUR7DAY,

        NC80HOUR8DAY,

        NC70HOUR7DAY,

        OK70HOUR8DAY,

        OK60HOUR7DAY,

        OR80HOUR8DAY,

        OR70HOUR7DAY,

        SC80HOUR8DAY,

        SC70HOUR7DAY,

        TX70HOUR7DAY,

        WI80HOUR8DAY,

        WI70HOUR7DAY,

        CANADA_SOUTH_CYCLE170HOUR7DAY,

        CANADA_SOUTH_CYCLE2120HOUR14DAY,

        CANADA_NORTH_CYCLE180HOUR7DAY,

        CANADA_NORTH_CYCLE2120HOUR14DAY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUsa60Hour7Day();

        T visitUsa70Hour8Day();

        T visitAk80Hour8Day();

        T visitAk70Hour7Day();

        T visitCa80Hour8Day();

        T visitCa112Hour8Day();

        T visitFl80Hour8Day();

        T visitFl70Hour7Day();

        T visitNe80Hour8Day();

        T visitNe70Hour7Day();

        T visitNc80Hour8Day();

        T visitNc70Hour7Day();

        T visitOk70Hour8Day();

        T visitOk60Hour7Day();

        T visitOr80Hour8Day();

        T visitOr70Hour7Day();

        T visitSc80Hour8Day();

        T visitSc70Hour7Day();

        T visitTx70Hour7Day();

        T visitWi80Hour8Day();

        T visitWi70Hour7Day();

        T visitCanadaSouthCycle170Hour7Day();

        T visitCanadaSouthCycle2120Hour14Day();

        T visitCanadaNorthCycle180Hour7Day();

        T visitCanadaNorthCycle2120Hour14Day();

        T visitUnknown(String unknownType);
    }
}
