/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class Dvir2RelatedDeviceObjectResponseBodyAssetType {
    public static final Dvir2RelatedDeviceObjectResponseBodyAssetType VEHICLE =
            new Dvir2RelatedDeviceObjectResponseBodyAssetType(Value.VEHICLE, "Vehicle");

    public static final Dvir2RelatedDeviceObjectResponseBodyAssetType TRAILER =
            new Dvir2RelatedDeviceObjectResponseBodyAssetType(Value.TRAILER, "Trailer");

    private final Value value;

    private final String string;

    Dvir2RelatedDeviceObjectResponseBodyAssetType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof Dvir2RelatedDeviceObjectResponseBodyAssetType
                        && this.string.equals(((Dvir2RelatedDeviceObjectResponseBodyAssetType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case VEHICLE:
                return visitor.visitVehicle();
            case TRAILER:
                return visitor.visitTrailer();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static Dvir2RelatedDeviceObjectResponseBodyAssetType valueOf(String value) {
        switch (value) {
            case "Vehicle":
                return VEHICLE;
            case "Trailer":
                return TRAILER;
            default:
                return new Dvir2RelatedDeviceObjectResponseBodyAssetType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        VEHICLE,

        TRAILER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitVehicle();

        T visitTrailer();

        T visitUnknown(String unknownType);
    }
}
