/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EntityListPartsTypeResponseBodyPartStatus {
    public static final EntityListPartsTypeResponseBodyPartStatus ACTIVE =
            new EntityListPartsTypeResponseBodyPartStatus(Value.ACTIVE, "Active");

    public static final EntityListPartsTypeResponseBodyPartStatus UNKNOWN =
            new EntityListPartsTypeResponseBodyPartStatus(Value.UNKNOWN, "Unknown");

    public static final EntityListPartsTypeResponseBodyPartStatus DELETED =
            new EntityListPartsTypeResponseBodyPartStatus(Value.DELETED, "Deleted");

    public static final EntityListPartsTypeResponseBodyPartStatus ARCHIVED =
            new EntityListPartsTypeResponseBodyPartStatus(Value.ARCHIVED, "Archived");

    private final Value value;

    private final String string;

    EntityListPartsTypeResponseBodyPartStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EntityListPartsTypeResponseBodyPartStatus
                        && this.string.equals(((EntityListPartsTypeResponseBodyPartStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ACTIVE:
                return visitor.visitActive();
            case UNKNOWN:
                return visitor.visitUnknown();
            case DELETED:
                return visitor.visitDeleted();
            case ARCHIVED:
                return visitor.visitArchived();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EntityListPartsTypeResponseBodyPartStatus valueOf(String value) {
        switch (value) {
            case "Active":
                return ACTIVE;
            case "Unknown":
                return UNKNOWN;
            case "Deleted":
                return DELETED;
            case "Archived":
                return ARCHIVED;
            default:
                return new EntityListPartsTypeResponseBodyPartStatus(Value._UNKNOWN, value);
        }
    }

    public enum Value {
        UNKNOWN,

        ACTIVE,

        ARCHIVED,

        DELETED,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnknown();

        T visitActive();

        T visitArchived();

        T visitDeleted();

        T visitUnknown(String unknownType);
    }
}
