/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HosViolationObjectResponseBody.Builder.class)
public final class HosViolationObjectResponseBody {
    private final HosViolationDayObjectResponseBody day;

    private final String description;

    private final GoaDriverTinyResponseResponseBody driver;

    private final long durationMs;

    private final HosViolationObjectResponseBodyType type;

    private final String violationStartTime;

    private final Map<String, Object> additionalProperties;

    private HosViolationObjectResponseBody(
            HosViolationDayObjectResponseBody day,
            String description,
            GoaDriverTinyResponseResponseBody driver,
            long durationMs,
            HosViolationObjectResponseBodyType type,
            String violationStartTime,
            Map<String, Object> additionalProperties) {
        this.day = day;
        this.description = description;
        this.driver = driver;
        this.durationMs = durationMs;
        this.type = type;
        this.violationStartTime = violationStartTime;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("day")
    public HosViolationDayObjectResponseBody getDay() {
        return day;
    }

    /**
     * @return Description containing violation type, region, and other metadata. This field can assume the following formats for the following types:
     * californiaMealbreakMissed, restbreakMissed: &quot;[description] ([max on duty hours] hours)&quot;
     * cycleHoursOn, dailyDrivingHours, dailyOffDutyNonResetHours, dailyOffDutyTotalHours, dailyOnDutyHours, shiftDrivingHours, shiftHours, shiftOnDutyHours: &quot;[description] ([region]-[max hours in duty status] hours)&quot;
     * cycleOffHoursAfterOnDutyHours: &quot;[description] ([region]): [minimum hours consecutive rest] hours off duty required after [max hours before consecutive rest] hours on-duty time&quot;
     * dailyOffDutyDeferralAddToDay2Consecutive, dailyOffDutyDeferralNotPartMandatory, dailyOffDutyDeferralTwoDayDrivingLimit, dailyOffDutyDeferralTwoDayOffDuty, mandatory24HoursOffDuty: &quot;[description] ([region])&quot;
     * unsubmittedLogs: &quot;Missing Driver Certification&quot;
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    @JsonProperty("driver")
    public GoaDriverTinyResponseResponseBody getDriver() {
        return driver;
    }

    /**
     * @return Duration the driver was in violation in milliseconds. This is the time between the time the driver starts being in violation until the end of the time window for violations that have one (e.g. <code>shiftDrivingHours</code>) or until the end of the day. The duration of some violations may cover the whole day (e.g. <code>unsubmittedLogs</code>).
     */
    @JsonProperty("durationMs")
    public long getDurationMs() {
        return durationMs;
    }

    /**
     * @return The string value of the violation type.  Valid values: <code>NONE</code>, <code>californiaMealbreakMissed</code>, <code>cycleHoursOn</code>, <code>cycleOffHoursAfterOnDutyHours</code>, <code>dailyDrivingHours</code>, <code>dailyOffDutyDeferralAddToDay2Consecutive</code>, <code>dailyOffDutyDeferralNotPartMandatory</code>, <code>dailyOffDutyDeferralTwoDayDrivingLimit</code>, <code>dailyOffDutyDeferralTwoDayOffDuty</code>, <code>dailyOffDutyNonResetHours</code>, <code>dailyOffDutyTotalHours</code>, <code>dailyOnDutyHours</code>, <code>mandatory24HoursOffDuty</code>, <code>restbreakMissed</code>, <code>shiftDrivingHours</code>, <code>shiftHours</code>, <code>shiftOnDutyHours</code>, <code>unsubmittedLogs</code>
     */
    @JsonProperty("type")
    public HosViolationObjectResponseBodyType getType() {
        return type;
    }

    /**
     * @return The start time of the violation in RFC 3339 format.
     */
    @JsonProperty("violationStartTime")
    public String getViolationStartTime() {
        return violationStartTime;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HosViolationObjectResponseBody && equalTo((HosViolationObjectResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HosViolationObjectResponseBody other) {
        return day.equals(other.day)
                && description.equals(other.description)
                && driver.equals(other.driver)
                && durationMs == other.durationMs
                && type.equals(other.type)
                && violationStartTime.equals(other.violationStartTime);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.day, this.description, this.driver, this.durationMs, this.type, this.violationStartTime);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DayStage builder() {
        return new Builder();
    }

    public interface DayStage {
        DescriptionStage day(@NotNull HosViolationDayObjectResponseBody day);

        Builder from(HosViolationObjectResponseBody other);
    }

    public interface DescriptionStage {
        /**
         * <p>Description containing violation type, region, and other metadata. This field can assume the following formats for the following types:
         * californiaMealbreakMissed, restbreakMissed: &quot;[description] ([max on duty hours] hours)&quot;
         * cycleHoursOn, dailyDrivingHours, dailyOffDutyNonResetHours, dailyOffDutyTotalHours, dailyOnDutyHours, shiftDrivingHours, shiftHours, shiftOnDutyHours: &quot;[description] ([region]-[max hours in duty status] hours)&quot;
         * cycleOffHoursAfterOnDutyHours: &quot;[description] ([region]): [minimum hours consecutive rest] hours off duty required after [max hours before consecutive rest] hours on-duty time&quot;
         * dailyOffDutyDeferralAddToDay2Consecutive, dailyOffDutyDeferralNotPartMandatory, dailyOffDutyDeferralTwoDayDrivingLimit, dailyOffDutyDeferralTwoDayOffDuty, mandatory24HoursOffDuty: &quot;[description] ([region])&quot;
         * unsubmittedLogs: &quot;Missing Driver Certification&quot;</p>
         */
        DriverStage description(@NotNull String description);
    }

    public interface DriverStage {
        DurationMsStage driver(@NotNull GoaDriverTinyResponseResponseBody driver);
    }

    public interface DurationMsStage {
        /**
         * <p>Duration the driver was in violation in milliseconds. This is the time between the time the driver starts being in violation until the end of the time window for violations that have one (e.g. <code>shiftDrivingHours</code>) or until the end of the day. The duration of some violations may cover the whole day (e.g. <code>unsubmittedLogs</code>).</p>
         */
        TypeStage durationMs(long durationMs);
    }

    public interface TypeStage {
        /**
         * <p>The string value of the violation type.  Valid values: <code>NONE</code>, <code>californiaMealbreakMissed</code>, <code>cycleHoursOn</code>, <code>cycleOffHoursAfterOnDutyHours</code>, <code>dailyDrivingHours</code>, <code>dailyOffDutyDeferralAddToDay2Consecutive</code>, <code>dailyOffDutyDeferralNotPartMandatory</code>, <code>dailyOffDutyDeferralTwoDayDrivingLimit</code>, <code>dailyOffDutyDeferralTwoDayOffDuty</code>, <code>dailyOffDutyNonResetHours</code>, <code>dailyOffDutyTotalHours</code>, <code>dailyOnDutyHours</code>, <code>mandatory24HoursOffDuty</code>, <code>restbreakMissed</code>, <code>shiftDrivingHours</code>, <code>shiftHours</code>, <code>shiftOnDutyHours</code>, <code>unsubmittedLogs</code></p>
         */
        ViolationStartTimeStage type(@NotNull HosViolationObjectResponseBodyType type);
    }

    public interface ViolationStartTimeStage {
        /**
         * <p>The start time of the violation in RFC 3339 format.</p>
         */
        _FinalStage violationStartTime(@NotNull String violationStartTime);
    }

    public interface _FinalStage {
        HosViolationObjectResponseBody build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements DayStage,
                    DescriptionStage,
                    DriverStage,
                    DurationMsStage,
                    TypeStage,
                    ViolationStartTimeStage,
                    _FinalStage {
        private HosViolationDayObjectResponseBody day;

        private String description;

        private GoaDriverTinyResponseResponseBody driver;

        private long durationMs;

        private HosViolationObjectResponseBodyType type;

        private String violationStartTime;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(HosViolationObjectResponseBody other) {
            day(other.getDay());
            description(other.getDescription());
            driver(other.getDriver());
            durationMs(other.getDurationMs());
            type(other.getType());
            violationStartTime(other.getViolationStartTime());
            return this;
        }

        @java.lang.Override
        @JsonSetter("day")
        public DescriptionStage day(@NotNull HosViolationDayObjectResponseBody day) {
            this.day = Objects.requireNonNull(day, "day must not be null");
            return this;
        }

        /**
         * <p>Description containing violation type, region, and other metadata. This field can assume the following formats for the following types:
         * californiaMealbreakMissed, restbreakMissed: &quot;[description] ([max on duty hours] hours)&quot;
         * cycleHoursOn, dailyDrivingHours, dailyOffDutyNonResetHours, dailyOffDutyTotalHours, dailyOnDutyHours, shiftDrivingHours, shiftHours, shiftOnDutyHours: &quot;[description] ([region]-[max hours in duty status] hours)&quot;
         * cycleOffHoursAfterOnDutyHours: &quot;[description] ([region]): [minimum hours consecutive rest] hours off duty required after [max hours before consecutive rest] hours on-duty time&quot;
         * dailyOffDutyDeferralAddToDay2Consecutive, dailyOffDutyDeferralNotPartMandatory, dailyOffDutyDeferralTwoDayDrivingLimit, dailyOffDutyDeferralTwoDayOffDuty, mandatory24HoursOffDuty: &quot;[description] ([region])&quot;
         * unsubmittedLogs: &quot;Missing Driver Certification&quot;</p>
         * <p>Description containing violation type, region, and other metadata. This field can assume the following formats for the following types:
         * californiaMealbreakMissed, restbreakMissed: &quot;[description] ([max on duty hours] hours)&quot;
         * cycleHoursOn, dailyDrivingHours, dailyOffDutyNonResetHours, dailyOffDutyTotalHours, dailyOnDutyHours, shiftDrivingHours, shiftHours, shiftOnDutyHours: &quot;[description] ([region]-[max hours in duty status] hours)&quot;
         * cycleOffHoursAfterOnDutyHours: &quot;[description] ([region]): [minimum hours consecutive rest] hours off duty required after [max hours before consecutive rest] hours on-duty time&quot;
         * dailyOffDutyDeferralAddToDay2Consecutive, dailyOffDutyDeferralNotPartMandatory, dailyOffDutyDeferralTwoDayDrivingLimit, dailyOffDutyDeferralTwoDayOffDuty, mandatory24HoursOffDuty: &quot;[description] ([region])&quot;
         * unsubmittedLogs: &quot;Missing Driver Certification&quot;</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public DriverStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("driver")
        public DurationMsStage driver(@NotNull GoaDriverTinyResponseResponseBody driver) {
            this.driver = Objects.requireNonNull(driver, "driver must not be null");
            return this;
        }

        /**
         * <p>Duration the driver was in violation in milliseconds. This is the time between the time the driver starts being in violation until the end of the time window for violations that have one (e.g. <code>shiftDrivingHours</code>) or until the end of the day. The duration of some violations may cover the whole day (e.g. <code>unsubmittedLogs</code>).</p>
         * <p>Duration the driver was in violation in milliseconds. This is the time between the time the driver starts being in violation until the end of the time window for violations that have one (e.g. <code>shiftDrivingHours</code>) or until the end of the day. The duration of some violations may cover the whole day (e.g. <code>unsubmittedLogs</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("durationMs")
        public TypeStage durationMs(long durationMs) {
            this.durationMs = durationMs;
            return this;
        }

        /**
         * <p>The string value of the violation type.  Valid values: <code>NONE</code>, <code>californiaMealbreakMissed</code>, <code>cycleHoursOn</code>, <code>cycleOffHoursAfterOnDutyHours</code>, <code>dailyDrivingHours</code>, <code>dailyOffDutyDeferralAddToDay2Consecutive</code>, <code>dailyOffDutyDeferralNotPartMandatory</code>, <code>dailyOffDutyDeferralTwoDayDrivingLimit</code>, <code>dailyOffDutyDeferralTwoDayOffDuty</code>, <code>dailyOffDutyNonResetHours</code>, <code>dailyOffDutyTotalHours</code>, <code>dailyOnDutyHours</code>, <code>mandatory24HoursOffDuty</code>, <code>restbreakMissed</code>, <code>shiftDrivingHours</code>, <code>shiftHours</code>, <code>shiftOnDutyHours</code>, <code>unsubmittedLogs</code></p>
         * <p>The string value of the violation type.  Valid values: <code>NONE</code>, <code>californiaMealbreakMissed</code>, <code>cycleHoursOn</code>, <code>cycleOffHoursAfterOnDutyHours</code>, <code>dailyDrivingHours</code>, <code>dailyOffDutyDeferralAddToDay2Consecutive</code>, <code>dailyOffDutyDeferralNotPartMandatory</code>, <code>dailyOffDutyDeferralTwoDayDrivingLimit</code>, <code>dailyOffDutyDeferralTwoDayOffDuty</code>, <code>dailyOffDutyNonResetHours</code>, <code>dailyOffDutyTotalHours</code>, <code>dailyOnDutyHours</code>, <code>mandatory24HoursOffDuty</code>, <code>restbreakMissed</code>, <code>shiftDrivingHours</code>, <code>shiftHours</code>, <code>shiftOnDutyHours</code>, <code>unsubmittedLogs</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public ViolationStartTimeStage type(@NotNull HosViolationObjectResponseBodyType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>The start time of the violation in RFC 3339 format.</p>
         * <p>The start time of the violation in RFC 3339 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("violationStartTime")
        public _FinalStage violationStartTime(@NotNull String violationStartTime) {
            this.violationStartTime = Objects.requireNonNull(violationStartTime, "violationStartTime must not be null");
            return this;
        }

        @java.lang.Override
        public HosViolationObjectResponseBody build() {
            return new HosViolationObjectResponseBody(
                    day, description, driver, durationMs, type, violationStartTime, additionalProperties);
        }
    }
}
