/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HubLocationObjectResponseBody.Builder.class)
public final class HubLocationObjectResponseBody {
    private final String address;

    private final OffsetDateTime createdAt;

    private final String customerLocationId;

    private final String driverInstructions;

    private final String hubId;

    private final String id;

    private final boolean isDepot;

    private final double latitude;

    private final double longitude;

    private final String name;

    private final String plannerNotes;

    private final int serviceTimeSeconds;

    private final List<ServiceWindowObjectResponseBody> serviceWindows;

    private final List<SkillObjectResponseBody> skillsRequired;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private HubLocationObjectResponseBody(
            String address,
            OffsetDateTime createdAt,
            String customerLocationId,
            String driverInstructions,
            String hubId,
            String id,
            boolean isDepot,
            double latitude,
            double longitude,
            String name,
            String plannerNotes,
            int serviceTimeSeconds,
            List<ServiceWindowObjectResponseBody> serviceWindows,
            List<SkillObjectResponseBody> skillsRequired,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.address = address;
        this.createdAt = createdAt;
        this.customerLocationId = customerLocationId;
        this.driverInstructions = driverInstructions;
        this.hubId = hubId;
        this.id = id;
        this.isDepot = isDepot;
        this.latitude = latitude;
        this.longitude = longitude;
        this.name = name;
        this.plannerNotes = plannerNotes;
        this.serviceTimeSeconds = serviceTimeSeconds;
        this.serviceWindows = serviceWindows;
        this.skillsRequired = skillsRequired;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The physical address of the location
     */
    @JsonProperty("address")
    public String getAddress() {
        return address;
    }

    /**
     * @return The timestamp (in UTC) when the location was created
     */
    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The customer-provided identifier for the location
     */
    @JsonProperty("customerLocationId")
    public String getCustomerLocationId() {
        return customerLocationId;
    }

    /**
     * @return Instructions for the driver
     */
    @JsonProperty("driverInstructions")
    public String getDriverInstructions() {
        return driverInstructions;
    }

    /**
     * @return The ID of the hub this location belongs to
     */
    @JsonProperty("hubId")
    public String getHubId() {
        return hubId;
    }

    /**
     * @return The Samsara-generated unique identifier (UUID) for the location
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Indicates if the location is a depot
     */
    @JsonProperty("isDepot")
    public boolean getIsDepot() {
        return isDepot;
    }

    /**
     * @return Latitude coordinate of the location
     */
    @JsonProperty("latitude")
    public double getLatitude() {
        return latitude;
    }

    /**
     * @return Longitude coordinate of the location
     */
    @JsonProperty("longitude")
    public double getLongitude() {
        return longitude;
    }

    /**
     * @return The name of the location
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Notes for the planner
     */
    @JsonProperty("plannerNotes")
    public String getPlannerNotes() {
        return plannerNotes;
    }

    /**
     * @return Estimated service time at this location in seconds
     */
    @JsonProperty("serviceTimeSeconds")
    public int getServiceTimeSeconds() {
        return serviceTimeSeconds;
    }

    /**
     * @return An array of time windows during which service can be performed at this location
     */
    @JsonProperty("serviceWindows")
    public List<ServiceWindowObjectResponseBody> getServiceWindows() {
        return serviceWindows;
    }

    /**
     * @return An array of skills required for service at this location
     */
    @JsonProperty("skillsRequired")
    public List<SkillObjectResponseBody> getSkillsRequired() {
        return skillsRequired;
    }

    /**
     * @return The timestamp (in UTC) when the location was last updated
     */
    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HubLocationObjectResponseBody && equalTo((HubLocationObjectResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HubLocationObjectResponseBody other) {
        return address.equals(other.address)
                && createdAt.equals(other.createdAt)
                && customerLocationId.equals(other.customerLocationId)
                && driverInstructions.equals(other.driverInstructions)
                && hubId.equals(other.hubId)
                && id.equals(other.id)
                && isDepot == other.isDepot
                && latitude == other.latitude
                && longitude == other.longitude
                && name.equals(other.name)
                && plannerNotes.equals(other.plannerNotes)
                && serviceTimeSeconds == other.serviceTimeSeconds
                && serviceWindows.equals(other.serviceWindows)
                && skillsRequired.equals(other.skillsRequired)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.address,
                this.createdAt,
                this.customerLocationId,
                this.driverInstructions,
                this.hubId,
                this.id,
                this.isDepot,
                this.latitude,
                this.longitude,
                this.name,
                this.plannerNotes,
                this.serviceTimeSeconds,
                this.serviceWindows,
                this.skillsRequired,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AddressStage builder() {
        return new Builder();
    }

    public interface AddressStage {
        /**
         * <p>The physical address of the location</p>
         */
        CreatedAtStage address(@NotNull String address);

        Builder from(HubLocationObjectResponseBody other);
    }

    public interface CreatedAtStage {
        /**
         * <p>The timestamp (in UTC) when the location was created</p>
         */
        CustomerLocationIdStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface CustomerLocationIdStage {
        /**
         * <p>The customer-provided identifier for the location</p>
         */
        DriverInstructionsStage customerLocationId(@NotNull String customerLocationId);
    }

    public interface DriverInstructionsStage {
        /**
         * <p>Instructions for the driver</p>
         */
        HubIdStage driverInstructions(@NotNull String driverInstructions);
    }

    public interface HubIdStage {
        /**
         * <p>The ID of the hub this location belongs to</p>
         */
        IdStage hubId(@NotNull String hubId);
    }

    public interface IdStage {
        /**
         * <p>The Samsara-generated unique identifier (UUID) for the location</p>
         */
        IsDepotStage id(@NotNull String id);
    }

    public interface IsDepotStage {
        /**
         * <p>Indicates if the location is a depot</p>
         */
        LatitudeStage isDepot(boolean isDepot);
    }

    public interface LatitudeStage {
        /**
         * <p>Latitude coordinate of the location</p>
         */
        LongitudeStage latitude(double latitude);
    }

    public interface LongitudeStage {
        /**
         * <p>Longitude coordinate of the location</p>
         */
        NameStage longitude(double longitude);
    }

    public interface NameStage {
        /**
         * <p>The name of the location</p>
         */
        PlannerNotesStage name(@NotNull String name);
    }

    public interface PlannerNotesStage {
        /**
         * <p>Notes for the planner</p>
         */
        ServiceTimeSecondsStage plannerNotes(@NotNull String plannerNotes);
    }

    public interface ServiceTimeSecondsStage {
        /**
         * <p>Estimated service time at this location in seconds</p>
         */
        UpdatedAtStage serviceTimeSeconds(int serviceTimeSeconds);
    }

    public interface UpdatedAtStage {
        /**
         * <p>The timestamp (in UTC) when the location was last updated</p>
         */
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        HubLocationObjectResponseBody build();

        /**
         * <p>An array of time windows during which service can be performed at this location</p>
         */
        _FinalStage serviceWindows(List<ServiceWindowObjectResponseBody> serviceWindows);

        _FinalStage addServiceWindows(ServiceWindowObjectResponseBody serviceWindows);

        _FinalStage addAllServiceWindows(List<ServiceWindowObjectResponseBody> serviceWindows);

        /**
         * <p>An array of skills required for service at this location</p>
         */
        _FinalStage skillsRequired(List<SkillObjectResponseBody> skillsRequired);

        _FinalStage addSkillsRequired(SkillObjectResponseBody skillsRequired);

        _FinalStage addAllSkillsRequired(List<SkillObjectResponseBody> skillsRequired);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements AddressStage,
                    CreatedAtStage,
                    CustomerLocationIdStage,
                    DriverInstructionsStage,
                    HubIdStage,
                    IdStage,
                    IsDepotStage,
                    LatitudeStage,
                    LongitudeStage,
                    NameStage,
                    PlannerNotesStage,
                    ServiceTimeSecondsStage,
                    UpdatedAtStage,
                    _FinalStage {
        private String address;

        private OffsetDateTime createdAt;

        private String customerLocationId;

        private String driverInstructions;

        private String hubId;

        private String id;

        private boolean isDepot;

        private double latitude;

        private double longitude;

        private String name;

        private String plannerNotes;

        private int serviceTimeSeconds;

        private OffsetDateTime updatedAt;

        private List<SkillObjectResponseBody> skillsRequired = new ArrayList<>();

        private List<ServiceWindowObjectResponseBody> serviceWindows = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(HubLocationObjectResponseBody other) {
            address(other.getAddress());
            createdAt(other.getCreatedAt());
            customerLocationId(other.getCustomerLocationId());
            driverInstructions(other.getDriverInstructions());
            hubId(other.getHubId());
            id(other.getId());
            isDepot(other.getIsDepot());
            latitude(other.getLatitude());
            longitude(other.getLongitude());
            name(other.getName());
            plannerNotes(other.getPlannerNotes());
            serviceTimeSeconds(other.getServiceTimeSeconds());
            serviceWindows(other.getServiceWindows());
            skillsRequired(other.getSkillsRequired());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>The physical address of the location</p>
         * <p>The physical address of the location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("address")
        public CreatedAtStage address(@NotNull String address) {
            this.address = Objects.requireNonNull(address, "address must not be null");
            return this;
        }

        /**
         * <p>The timestamp (in UTC) when the location was created</p>
         * <p>The timestamp (in UTC) when the location was created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public CustomerLocationIdStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>The customer-provided identifier for the location</p>
         * <p>The customer-provided identifier for the location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("customerLocationId")
        public DriverInstructionsStage customerLocationId(@NotNull String customerLocationId) {
            this.customerLocationId = Objects.requireNonNull(customerLocationId, "customerLocationId must not be null");
            return this;
        }

        /**
         * <p>Instructions for the driver</p>
         * <p>Instructions for the driver</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("driverInstructions")
        public HubIdStage driverInstructions(@NotNull String driverInstructions) {
            this.driverInstructions = Objects.requireNonNull(driverInstructions, "driverInstructions must not be null");
            return this;
        }

        /**
         * <p>The ID of the hub this location belongs to</p>
         * <p>The ID of the hub this location belongs to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("hubId")
        public IdStage hubId(@NotNull String hubId) {
            this.hubId = Objects.requireNonNull(hubId, "hubId must not be null");
            return this;
        }

        /**
         * <p>The Samsara-generated unique identifier (UUID) for the location</p>
         * <p>The Samsara-generated unique identifier (UUID) for the location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public IsDepotStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Indicates if the location is a depot</p>
         * <p>Indicates if the location is a depot</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("isDepot")
        public LatitudeStage isDepot(boolean isDepot) {
            this.isDepot = isDepot;
            return this;
        }

        /**
         * <p>Latitude coordinate of the location</p>
         * <p>Latitude coordinate of the location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("latitude")
        public LongitudeStage latitude(double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * <p>Longitude coordinate of the location</p>
         * <p>Longitude coordinate of the location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("longitude")
        public NameStage longitude(double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * <p>The name of the location</p>
         * <p>The name of the location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public PlannerNotesStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Notes for the planner</p>
         * <p>Notes for the planner</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("plannerNotes")
        public ServiceTimeSecondsStage plannerNotes(@NotNull String plannerNotes) {
            this.plannerNotes = Objects.requireNonNull(plannerNotes, "plannerNotes must not be null");
            return this;
        }

        /**
         * <p>Estimated service time at this location in seconds</p>
         * <p>Estimated service time at this location in seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("serviceTimeSeconds")
        public UpdatedAtStage serviceTimeSeconds(int serviceTimeSeconds) {
            this.serviceTimeSeconds = serviceTimeSeconds;
            return this;
        }

        /**
         * <p>The timestamp (in UTC) when the location was last updated</p>
         * <p>The timestamp (in UTC) when the location was last updated</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>An array of skills required for service at this location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllSkillsRequired(List<SkillObjectResponseBody> skillsRequired) {
            if (skillsRequired != null) {
                this.skillsRequired.addAll(skillsRequired);
            }
            return this;
        }

        /**
         * <p>An array of skills required for service at this location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addSkillsRequired(SkillObjectResponseBody skillsRequired) {
            this.skillsRequired.add(skillsRequired);
            return this;
        }

        /**
         * <p>An array of skills required for service at this location</p>
         */
        @java.lang.Override
        @JsonSetter(value = "skillsRequired", nulls = Nulls.SKIP)
        public _FinalStage skillsRequired(List<SkillObjectResponseBody> skillsRequired) {
            this.skillsRequired.clear();
            if (skillsRequired != null) {
                this.skillsRequired.addAll(skillsRequired);
            }
            return this;
        }

        /**
         * <p>An array of time windows during which service can be performed at this location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllServiceWindows(List<ServiceWindowObjectResponseBody> serviceWindows) {
            if (serviceWindows != null) {
                this.serviceWindows.addAll(serviceWindows);
            }
            return this;
        }

        /**
         * <p>An array of time windows during which service can be performed at this location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addServiceWindows(ServiceWindowObjectResponseBody serviceWindows) {
            this.serviceWindows.add(serviceWindows);
            return this;
        }

        /**
         * <p>An array of time windows during which service can be performed at this location</p>
         */
        @java.lang.Override
        @JsonSetter(value = "serviceWindows", nulls = Nulls.SKIP)
        public _FinalStage serviceWindows(List<ServiceWindowObjectResponseBody> serviceWindows) {
            this.serviceWindows.clear();
            if (serviceWindows != null) {
                this.serviceWindows.addAll(serviceWindows);
            }
            return this;
        }

        @java.lang.Override
        public HubLocationObjectResponseBody build() {
            return new HubLocationObjectResponseBody(
                    address,
                    createdAt,
                    customerLocationId,
                    driverInstructions,
                    hubId,
                    id,
                    isDepot,
                    latitude,
                    longitude,
                    name,
                    plannerNotes,
                    serviceTimeSeconds,
                    serviceWindows,
                    skillsRequired,
                    updatedAt,
                    additionalProperties);
        }
    }
}
