/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import java.util.List;
import java.util.Optional;

public interface IV1TrailerAssignmentsResponseAllOf {
    Optional<List<V1TrailerAssignmentResponse>> getTrailerAssignments();
}
