/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody.Builder.class)
public final class ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody {
    private final Optional<String> id;

    private final Optional<String> itemType;

    private final Optional<String> vmrsCode;

    private final Map<String, Object> additionalProperties;

    private ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody(
            Optional<String> id,
            Optional<String> itemType,
            Optional<String> vmrsCode,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.itemType = itemType;
        this.vmrsCode = vmrsCode;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Identifier of the covered item. For a service task item this is the service task definition key. For a VMRS code item supply vmrsCode instead, or this internal VMRS code ID.
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return Kind of covered item, indicating how the ID should be interpreted (VMRS code or service task).
     */
    @JsonProperty("itemType")
    public Optional<String> getItemType() {
        return itemType;
    }

    /**
     * @return Dotted VMRS code path (e.g. 034-005-001). Use with itemType vmrsCode instead of id.
     */
    @JsonProperty("vmrsCode")
    public Optional<String> getVmrsCode() {
        return vmrsCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody
                && equalTo((ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody other) {
        return id.equals(other.id) && itemType.equals(other.itemType) && vmrsCode.equals(other.vmrsCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.itemType, this.vmrsCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> itemType = Optional.empty();

        private Optional<String> vmrsCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody other) {
            id(other.getId());
            itemType(other.getItemType());
            vmrsCode(other.getVmrsCode());
            return this;
        }

        /**
         * <p>Identifier of the covered item. For a service task item this is the service task definition key. For a VMRS code item supply vmrsCode instead, or this internal VMRS code ID.</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Kind of covered item, indicating how the ID should be interpreted (VMRS code or service task).</p>
         */
        @JsonSetter(value = "itemType", nulls = Nulls.SKIP)
        public Builder itemType(Optional<String> itemType) {
            this.itemType = itemType;
            return this;
        }

        public Builder itemType(String itemType) {
            this.itemType = Optional.ofNullable(itemType);
            return this;
        }

        /**
         * <p>Dotted VMRS code path (e.g. 034-005-001). Use with itemType vmrsCode instead of id.</p>
         */
        @JsonSetter(value = "vmrsCode", nulls = Nulls.SKIP)
        public Builder vmrsCode(Optional<String> vmrsCode) {
            this.vmrsCode = vmrsCode;
            return this;
        }

        public Builder vmrsCode(String vmrsCode) {
            this.vmrsCode = Optional.ofNullable(vmrsCode);
            return this;
        }

        public ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody build() {
            return new ListWarrantiesEntityWarrantyWarrantyCoverageItemTypeResponseBody(
                    id, itemType, vmrsCode, additionalProperties);
        }
    }
}
