/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LiveSharingLinkFullResponseObjectResponseBodyType {
    public static final LiveSharingLinkFullResponseObjectResponseBodyType ASSETS_NEAR_LOCATION =
            new LiveSharingLinkFullResponseObjectResponseBodyType(Value.ASSETS_NEAR_LOCATION, "assetsNearLocation");

    public static final LiveSharingLinkFullResponseObjectResponseBodyType ASSETS_LOCATION =
            new LiveSharingLinkFullResponseObjectResponseBodyType(Value.ASSETS_LOCATION, "assetsLocation");

    public static final LiveSharingLinkFullResponseObjectResponseBodyType ASSETS_ON_ROUTE =
            new LiveSharingLinkFullResponseObjectResponseBodyType(Value.ASSETS_ON_ROUTE, "assetsOnRoute");

    private final Value value;

    private final String string;

    LiveSharingLinkFullResponseObjectResponseBodyType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LiveSharingLinkFullResponseObjectResponseBodyType
                        && this.string.equals(((LiveSharingLinkFullResponseObjectResponseBodyType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ASSETS_NEAR_LOCATION:
                return visitor.visitAssetsNearLocation();
            case ASSETS_LOCATION:
                return visitor.visitAssetsLocation();
            case ASSETS_ON_ROUTE:
                return visitor.visitAssetsOnRoute();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LiveSharingLinkFullResponseObjectResponseBodyType valueOf(String value) {
        switch (value) {
            case "assetsNearLocation":
                return ASSETS_NEAR_LOCATION;
            case "assetsLocation":
                return ASSETS_LOCATION;
            case "assetsOnRoute":
                return ASSETS_ON_ROUTE;
            default:
                return new LiveSharingLinkFullResponseObjectResponseBodyType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ASSETS_LOCATION,

        ASSETS_NEAR_LOCATION,

        ASSETS_ON_ROUTE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAssetsLocation();

        T visitAssetsNearLocation();

        T visitAssetsOnRoute();

        T visitUnknown(String unknownType);
    }
}
