/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class MediaObjectResponseBodyStatus {
    public static final MediaObjectResponseBodyStatus INVALID =
            new MediaObjectResponseBodyStatus(Value.INVALID, "invalid");

    public static final MediaObjectResponseBodyStatus FAILED =
            new MediaObjectResponseBodyStatus(Value.FAILED, "failed");

    public static final MediaObjectResponseBodyStatus UNAVAILABLE =
            new MediaObjectResponseBodyStatus(Value.UNAVAILABLE, "unavailable");

    public static final MediaObjectResponseBodyStatus AVAILABLE =
            new MediaObjectResponseBodyStatus(Value.AVAILABLE, "available");

    public static final MediaObjectResponseBodyStatus PENDING =
            new MediaObjectResponseBodyStatus(Value.PENDING, "pending");

    private final Value value;

    private final String string;

    MediaObjectResponseBodyStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof MediaObjectResponseBodyStatus
                        && this.string.equals(((MediaObjectResponseBodyStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case INVALID:
                return visitor.visitInvalid();
            case FAILED:
                return visitor.visitFailed();
            case UNAVAILABLE:
                return visitor.visitUnavailable();
            case AVAILABLE:
                return visitor.visitAvailable();
            case PENDING:
                return visitor.visitPending();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static MediaObjectResponseBodyStatus valueOf(String value) {
        switch (value) {
            case "invalid":
                return INVALID;
            case "failed":
                return FAILED;
            case "unavailable":
                return UNAVAILABLE;
            case "available":
                return AVAILABLE;
            case "pending":
                return PENDING;
            default:
                return new MediaObjectResponseBodyStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AVAILABLE,

        INVALID,

        PENDING,

        FAILED,

        UNAVAILABLE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAvailable();

        T visitInvalid();

        T visitPending();

        T visitFailed();

        T visitUnavailable();

        T visitUnknown(String unknownType);
    }
}
