/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MinimalRouteStopResponseBody.Builder.class)
public final class MinimalRouteStopResponseBody {
    private final Optional<OffsetDateTime> actualArrivalTime;

    private final Optional<OffsetDateTime> actualDepartureTime;

    private final Optional<OffsetDateTime> enRouteTime;

    private final Optional<OffsetDateTime> eta;

    private final Optional<Map<String, String>> externalIds;

    private final String id;

    private final Optional<String> liveSharingUrl;

    private final Optional<OffsetDateTime> skippedTime;

    private final MinimalRouteStopResponseBodyState state;

    private final Map<String, Object> additionalProperties;

    private MinimalRouteStopResponseBody(
            Optional<OffsetDateTime> actualArrivalTime,
            Optional<OffsetDateTime> actualDepartureTime,
            Optional<OffsetDateTime> enRouteTime,
            Optional<OffsetDateTime> eta,
            Optional<Map<String, String>> externalIds,
            String id,
            Optional<String> liveSharingUrl,
            Optional<OffsetDateTime> skippedTime,
            MinimalRouteStopResponseBodyState state,
            Map<String, Object> additionalProperties) {
        this.actualArrivalTime = actualArrivalTime;
        this.actualDepartureTime = actualDepartureTime;
        this.enRouteTime = enRouteTime;
        this.eta = eta;
        this.externalIds = externalIds;
        this.id = id;
        this.liveSharingUrl = liveSharingUrl;
        this.skippedTime = skippedTime;
        this.state = state;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Actual arrival time, if it exists, for the route stop in RFC 3339 format.
     */
    @JsonProperty("actualArrivalTime")
    public Optional<OffsetDateTime> getActualArrivalTime() {
        return actualArrivalTime;
    }

    /**
     * @return Actual departure time, if it exists, for the route stop in RFC 3339 format.
     */
    @JsonProperty("actualDepartureTime")
    public Optional<OffsetDateTime> getActualDepartureTime() {
        return actualDepartureTime;
    }

    /**
     * @return The time the stop became en-route, in RFC 3339 format.
     */
    @JsonProperty("enRouteTime")
    public Optional<OffsetDateTime> getEnRouteTime() {
        return enRouteTime;
    }

    /**
     * @return Estimated time of arrival, if this stop is currently en-route, in RFC 3339 format.
     */
    @JsonProperty("eta")
    public Optional<OffsetDateTime> getEta() {
        return eta;
    }

    /**
     * @return A map of external ids
     */
    @JsonProperty("externalIds")
    public Optional<Map<String, String>> getExternalIds() {
        return externalIds;
    }

    /**
     * @return Unique identifier for the route stop.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The shareable url of the stop's current status.
     */
    @JsonProperty("liveSharingUrl")
    public Optional<String> getLiveSharingUrl() {
        return liveSharingUrl;
    }

    /**
     * @return Skipped time, if it exists, for the route stop in RFC 3339 format.
     */
    @JsonProperty("skippedTime")
    public Optional<OffsetDateTime> getSkippedTime() {
        return skippedTime;
    }

    /**
     * @return The current state of the route stop.  Valid values: <code>unassigned</code>, <code>scheduled</code>, <code>en route</code>, <code>skipped</code>, <code>arrived</code>, <code>departed</code>
     */
    @JsonProperty("state")
    public MinimalRouteStopResponseBodyState getState() {
        return state;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MinimalRouteStopResponseBody && equalTo((MinimalRouteStopResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MinimalRouteStopResponseBody other) {
        return actualArrivalTime.equals(other.actualArrivalTime)
                && actualDepartureTime.equals(other.actualDepartureTime)
                && enRouteTime.equals(other.enRouteTime)
                && eta.equals(other.eta)
                && externalIds.equals(other.externalIds)
                && id.equals(other.id)
                && liveSharingUrl.equals(other.liveSharingUrl)
                && skippedTime.equals(other.skippedTime)
                && state.equals(other.state);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.actualArrivalTime,
                this.actualDepartureTime,
                this.enRouteTime,
                this.eta,
                this.externalIds,
                this.id,
                this.liveSharingUrl,
                this.skippedTime,
                this.state);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique identifier for the route stop.</p>
         */
        StateStage id(@NotNull String id);

        Builder from(MinimalRouteStopResponseBody other);
    }

    public interface StateStage {
        /**
         * <p>The current state of the route stop.  Valid values: <code>unassigned</code>, <code>scheduled</code>, <code>en route</code>, <code>skipped</code>, <code>arrived</code>, <code>departed</code></p>
         */
        _FinalStage state(@NotNull MinimalRouteStopResponseBodyState state);
    }

    public interface _FinalStage {
        MinimalRouteStopResponseBody build();

        /**
         * <p>Actual arrival time, if it exists, for the route stop in RFC 3339 format.</p>
         */
        _FinalStage actualArrivalTime(Optional<OffsetDateTime> actualArrivalTime);

        _FinalStage actualArrivalTime(OffsetDateTime actualArrivalTime);

        /**
         * <p>Actual departure time, if it exists, for the route stop in RFC 3339 format.</p>
         */
        _FinalStage actualDepartureTime(Optional<OffsetDateTime> actualDepartureTime);

        _FinalStage actualDepartureTime(OffsetDateTime actualDepartureTime);

        /**
         * <p>The time the stop became en-route, in RFC 3339 format.</p>
         */
        _FinalStage enRouteTime(Optional<OffsetDateTime> enRouteTime);

        _FinalStage enRouteTime(OffsetDateTime enRouteTime);

        /**
         * <p>Estimated time of arrival, if this stop is currently en-route, in RFC 3339 format.</p>
         */
        _FinalStage eta(Optional<OffsetDateTime> eta);

        _FinalStage eta(OffsetDateTime eta);

        /**
         * <p>A map of external ids</p>
         */
        _FinalStage externalIds(Optional<Map<String, String>> externalIds);

        _FinalStage externalIds(Map<String, String> externalIds);

        /**
         * <p>The shareable url of the stop's current status.</p>
         */
        _FinalStage liveSharingUrl(Optional<String> liveSharingUrl);

        _FinalStage liveSharingUrl(String liveSharingUrl);

        /**
         * <p>Skipped time, if it exists, for the route stop in RFC 3339 format.</p>
         */
        _FinalStage skippedTime(Optional<OffsetDateTime> skippedTime);

        _FinalStage skippedTime(OffsetDateTime skippedTime);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, StateStage, _FinalStage {
        private String id;

        private MinimalRouteStopResponseBodyState state;

        private Optional<OffsetDateTime> skippedTime = Optional.empty();

        private Optional<String> liveSharingUrl = Optional.empty();

        private Optional<Map<String, String>> externalIds = Optional.empty();

        private Optional<OffsetDateTime> eta = Optional.empty();

        private Optional<OffsetDateTime> enRouteTime = Optional.empty();

        private Optional<OffsetDateTime> actualDepartureTime = Optional.empty();

        private Optional<OffsetDateTime> actualArrivalTime = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MinimalRouteStopResponseBody other) {
            actualArrivalTime(other.getActualArrivalTime());
            actualDepartureTime(other.getActualDepartureTime());
            enRouteTime(other.getEnRouteTime());
            eta(other.getEta());
            externalIds(other.getExternalIds());
            id(other.getId());
            liveSharingUrl(other.getLiveSharingUrl());
            skippedTime(other.getSkippedTime());
            state(other.getState());
            return this;
        }

        /**
         * <p>Unique identifier for the route stop.</p>
         * <p>Unique identifier for the route stop.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public StateStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The current state of the route stop.  Valid values: <code>unassigned</code>, <code>scheduled</code>, <code>en route</code>, <code>skipped</code>, <code>arrived</code>, <code>departed</code></p>
         * <p>The current state of the route stop.  Valid values: <code>unassigned</code>, <code>scheduled</code>, <code>en route</code>, <code>skipped</code>, <code>arrived</code>, <code>departed</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("state")
        public _FinalStage state(@NotNull MinimalRouteStopResponseBodyState state) {
            this.state = Objects.requireNonNull(state, "state must not be null");
            return this;
        }

        /**
         * <p>Skipped time, if it exists, for the route stop in RFC 3339 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage skippedTime(OffsetDateTime skippedTime) {
            this.skippedTime = Optional.ofNullable(skippedTime);
            return this;
        }

        /**
         * <p>Skipped time, if it exists, for the route stop in RFC 3339 format.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "skippedTime", nulls = Nulls.SKIP)
        public _FinalStage skippedTime(Optional<OffsetDateTime> skippedTime) {
            this.skippedTime = skippedTime;
            return this;
        }

        /**
         * <p>The shareable url of the stop's current status.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage liveSharingUrl(String liveSharingUrl) {
            this.liveSharingUrl = Optional.ofNullable(liveSharingUrl);
            return this;
        }

        /**
         * <p>The shareable url of the stop's current status.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "liveSharingUrl", nulls = Nulls.SKIP)
        public _FinalStage liveSharingUrl(Optional<String> liveSharingUrl) {
            this.liveSharingUrl = liveSharingUrl;
            return this;
        }

        /**
         * <p>A map of external ids</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalIds(Map<String, String> externalIds) {
            this.externalIds = Optional.ofNullable(externalIds);
            return this;
        }

        /**
         * <p>A map of external ids</p>
         */
        @java.lang.Override
        @JsonSetter(value = "externalIds", nulls = Nulls.SKIP)
        public _FinalStage externalIds(Optional<Map<String, String>> externalIds) {
            this.externalIds = externalIds;
            return this;
        }

        /**
         * <p>Estimated time of arrival, if this stop is currently en-route, in RFC 3339 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage eta(OffsetDateTime eta) {
            this.eta = Optional.ofNullable(eta);
            return this;
        }

        /**
         * <p>Estimated time of arrival, if this stop is currently en-route, in RFC 3339 format.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "eta", nulls = Nulls.SKIP)
        public _FinalStage eta(Optional<OffsetDateTime> eta) {
            this.eta = eta;
            return this;
        }

        /**
         * <p>The time the stop became en-route, in RFC 3339 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage enRouteTime(OffsetDateTime enRouteTime) {
            this.enRouteTime = Optional.ofNullable(enRouteTime);
            return this;
        }

        /**
         * <p>The time the stop became en-route, in RFC 3339 format.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "enRouteTime", nulls = Nulls.SKIP)
        public _FinalStage enRouteTime(Optional<OffsetDateTime> enRouteTime) {
            this.enRouteTime = enRouteTime;
            return this;
        }

        /**
         * <p>Actual departure time, if it exists, for the route stop in RFC 3339 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage actualDepartureTime(OffsetDateTime actualDepartureTime) {
            this.actualDepartureTime = Optional.ofNullable(actualDepartureTime);
            return this;
        }

        /**
         * <p>Actual departure time, if it exists, for the route stop in RFC 3339 format.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "actualDepartureTime", nulls = Nulls.SKIP)
        public _FinalStage actualDepartureTime(Optional<OffsetDateTime> actualDepartureTime) {
            this.actualDepartureTime = actualDepartureTime;
            return this;
        }

        /**
         * <p>Actual arrival time, if it exists, for the route stop in RFC 3339 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage actualArrivalTime(OffsetDateTime actualArrivalTime) {
            this.actualArrivalTime = Optional.ofNullable(actualArrivalTime);
            return this;
        }

        /**
         * <p>Actual arrival time, if it exists, for the route stop in RFC 3339 format.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "actualArrivalTime", nulls = Nulls.SKIP)
        public _FinalStage actualArrivalTime(Optional<OffsetDateTime> actualArrivalTime) {
            this.actualArrivalTime = actualArrivalTime;
            return this;
        }

        @java.lang.Override
        public MinimalRouteStopResponseBody build() {
            return new MinimalRouteStopResponseBody(
                    actualArrivalTime,
                    actualDepartureTime,
                    enRouteTime,
                    eta,
                    externalIds,
                    id,
                    liveSharingUrl,
                    skippedTime,
                    state,
                    additionalProperties);
        }
    }
}
