/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RouteSettingsRequestBodyRouteStartingCondition {
    public static final RouteSettingsRequestBodyRouteStartingCondition DEPART_FIRST_STOP =
            new RouteSettingsRequestBodyRouteStartingCondition(Value.DEPART_FIRST_STOP, "departFirstStop");

    public static final RouteSettingsRequestBodyRouteStartingCondition ARRIVE_FIRST_STOP =
            new RouteSettingsRequestBodyRouteStartingCondition(Value.ARRIVE_FIRST_STOP, "arriveFirstStop");

    private final Value value;

    private final String string;

    RouteSettingsRequestBodyRouteStartingCondition(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RouteSettingsRequestBodyRouteStartingCondition
                        && this.string.equals(((RouteSettingsRequestBodyRouteStartingCondition) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DEPART_FIRST_STOP:
                return visitor.visitDepartFirstStop();
            case ARRIVE_FIRST_STOP:
                return visitor.visitArriveFirstStop();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RouteSettingsRequestBodyRouteStartingCondition valueOf(String value) {
        switch (value) {
            case "departFirstStop":
                return DEPART_FIRST_STOP;
            case "arriveFirstStop":
                return ARRIVE_FIRST_STOP;
            default:
                return new RouteSettingsRequestBodyRouteStartingCondition(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DEPART_FIRST_STOP,

        ARRIVE_FIRST_STOP,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDepartFirstStop();

        T visitArriveFirstStop();

        T visitUnknown(String unknownType);
    }
}
