/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SafetyEventV2DriverObjectResponseBody.Builder.class)
public final class SafetyEventV2DriverObjectResponseBody {
    private final Optional<List<GoaAttributeTinyResponseBody>> attributes;

    private final Optional<Map<String, String>> externalIds;

    private final String id;

    private final Optional<String> name;

    private final Optional<List<GoaTagTinyResponseResponseBody>> tags;

    private final Map<String, Object> additionalProperties;

    private SafetyEventV2DriverObjectResponseBody(
            Optional<List<GoaAttributeTinyResponseBody>> attributes,
            Optional<Map<String, String>> externalIds,
            String id,
            Optional<String> name,
            Optional<List<GoaTagTinyResponseResponseBody>> tags,
            Map<String, Object> additionalProperties) {
        this.attributes = attributes;
        this.externalIds = externalIds;
        this.id = id;
        this.name = name;
        this.tags = tags;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Attributes for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.
     */
    @JsonProperty("attributes")
    public Optional<List<GoaAttributeTinyResponseBody>> getAttributes() {
        return attributes;
    }

    /**
     * @return A map of external ids
     */
    @JsonProperty("externalIds")
    public Optional<Map<String, String>> getExternalIds() {
        return externalIds;
    }

    /**
     * @return Unique ID for the driver object that is assigned to the safety event.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Name of the driver. Only returns when <code>includeDriver</code> is set to <code>true</code>.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Tags for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.
     */
    @JsonProperty("tags")
    public Optional<List<GoaTagTinyResponseResponseBody>> getTags() {
        return tags;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SafetyEventV2DriverObjectResponseBody
                && equalTo((SafetyEventV2DriverObjectResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SafetyEventV2DriverObjectResponseBody other) {
        return attributes.equals(other.attributes)
                && externalIds.equals(other.externalIds)
                && id.equals(other.id)
                && name.equals(other.name)
                && tags.equals(other.tags);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.attributes, this.externalIds, this.id, this.name, this.tags);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique ID for the driver object that is assigned to the safety event.</p>
         */
        _FinalStage id(@NotNull String id);

        Builder from(SafetyEventV2DriverObjectResponseBody other);
    }

    public interface _FinalStage {
        SafetyEventV2DriverObjectResponseBody build();

        /**
         * <p>Attributes for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         */
        _FinalStage attributes(Optional<List<GoaAttributeTinyResponseBody>> attributes);

        _FinalStage attributes(List<GoaAttributeTinyResponseBody> attributes);

        /**
         * <p>A map of external ids</p>
         */
        _FinalStage externalIds(Optional<Map<String, String>> externalIds);

        _FinalStage externalIds(Map<String, String> externalIds);

        /**
         * <p>Name of the driver. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         */
        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        /**
         * <p>Tags for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         */
        _FinalStage tags(Optional<List<GoaTagTinyResponseResponseBody>> tags);

        _FinalStage tags(List<GoaTagTinyResponseResponseBody> tags);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, _FinalStage {
        private String id;

        private Optional<List<GoaTagTinyResponseResponseBody>> tags = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<Map<String, String>> externalIds = Optional.empty();

        private Optional<List<GoaAttributeTinyResponseBody>> attributes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SafetyEventV2DriverObjectResponseBody other) {
            attributes(other.getAttributes());
            externalIds(other.getExternalIds());
            id(other.getId());
            name(other.getName());
            tags(other.getTags());
            return this;
        }

        /**
         * <p>Unique ID for the driver object that is assigned to the safety event.</p>
         * <p>Unique ID for the driver object that is assigned to the safety event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public _FinalStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Tags for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage tags(List<GoaTagTinyResponseResponseBody> tags) {
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        /**
         * <p>Tags for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "tags", nulls = Nulls.SKIP)
        public _FinalStage tags(Optional<List<GoaTagTinyResponseResponseBody>> tags) {
            this.tags = tags;
            return this;
        }

        /**
         * <p>Name of the driver. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Name of the driver. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        /**
         * <p>A map of external ids</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalIds(Map<String, String> externalIds) {
            this.externalIds = Optional.ofNullable(externalIds);
            return this;
        }

        /**
         * <p>A map of external ids</p>
         */
        @java.lang.Override
        @JsonSetter(value = "externalIds", nulls = Nulls.SKIP)
        public _FinalStage externalIds(Optional<Map<String, String>> externalIds) {
            this.externalIds = externalIds;
            return this;
        }

        /**
         * <p>Attributes for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage attributes(List<GoaAttributeTinyResponseBody> attributes) {
            this.attributes = Optional.ofNullable(attributes);
            return this;
        }

        /**
         * <p>Attributes for the driver associated with the safety event. Only returns when <code>includeDriver</code> is set to <code>true</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "attributes", nulls = Nulls.SKIP)
        public _FinalStage attributes(Optional<List<GoaAttributeTinyResponseBody>> attributes) {
            this.attributes = attributes;
            return this;
        }

        @java.lang.Override
        public SafetyEventV2DriverObjectResponseBody build() {
            return new SafetyEventV2DriverObjectResponseBody(
                    attributes, externalIds, id, name, tags, additionalProperties);
        }
    }
}
