/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SafetyEventV2AssetObjectResponseBodyType {
    public static final SafetyEventV2AssetObjectResponseBodyType UNPOWERED =
            new SafetyEventV2AssetObjectResponseBodyType(Value.UNPOWERED, "unpowered");

    public static final SafetyEventV2AssetObjectResponseBodyType VEHICLE =
            new SafetyEventV2AssetObjectResponseBodyType(Value.VEHICLE, "vehicle");

    public static final SafetyEventV2AssetObjectResponseBodyType UNCATEGORIZED =
            new SafetyEventV2AssetObjectResponseBodyType(Value.UNCATEGORIZED, "uncategorized");

    public static final SafetyEventV2AssetObjectResponseBodyType TRAILER =
            new SafetyEventV2AssetObjectResponseBodyType(Value.TRAILER, "trailer");

    public static final SafetyEventV2AssetObjectResponseBodyType EQUIPMENT =
            new SafetyEventV2AssetObjectResponseBodyType(Value.EQUIPMENT, "equipment");

    private final Value value;

    private final String string;

    SafetyEventV2AssetObjectResponseBodyType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SafetyEventV2AssetObjectResponseBodyType
                        && this.string.equals(((SafetyEventV2AssetObjectResponseBodyType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UNPOWERED:
                return visitor.visitUnpowered();
            case VEHICLE:
                return visitor.visitVehicle();
            case UNCATEGORIZED:
                return visitor.visitUncategorized();
            case TRAILER:
                return visitor.visitTrailer();
            case EQUIPMENT:
                return visitor.visitEquipment();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SafetyEventV2AssetObjectResponseBodyType valueOf(String value) {
        switch (value) {
            case "unpowered":
                return UNPOWERED;
            case "vehicle":
                return VEHICLE;
            case "uncategorized":
                return UNCATEGORIZED;
            case "trailer":
                return TRAILER;
            case "equipment":
                return EQUIPMENT;
            default:
                return new SafetyEventV2AssetObjectResponseBodyType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        UNCATEGORIZED,

        TRAILER,

        EQUIPMENT,

        UNPOWERED,

        VEHICLE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUncategorized();

        T visitTrailer();

        T visitEquipment();

        T visitUnpowered();

        T visitVehicle();

        T visitUnknown(String unknownType);
    }
}
