/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpeedTriggerDetailsObjectResponseBody.Builder.class)
public final class SpeedTriggerDetailsObjectResponseBody {
    private final long minDurationMilliseconds;

    private final SpeedTriggerDetailsObjectResponseBodyOperation operation;

    private final long speedKilometersPerHour;

    private final Map<String, Object> additionalProperties;

    private SpeedTriggerDetailsObjectResponseBody(
            long minDurationMilliseconds,
            SpeedTriggerDetailsObjectResponseBodyOperation operation,
            long speedKilometersPerHour,
            Map<String, Object> additionalProperties) {
        this.minDurationMilliseconds = minDurationMilliseconds;
        this.operation = operation;
        this.speedKilometersPerHour = speedKilometersPerHour;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The number of milliseconds the trigger needs to stay active before alerting.
     */
    @JsonProperty("minDurationMilliseconds")
    public long getMinDurationMilliseconds() {
        return minDurationMilliseconds;
    }

    /**
     * @return How to evaluate the threshold.  Valid values: <code>GREATER</code>, <code>LESS</code>
     */
    @JsonProperty("operation")
    public SpeedTriggerDetailsObjectResponseBodyOperation getOperation() {
        return operation;
    }

    /**
     * @return The speed threshold value.
     */
    @JsonProperty("speedKilometersPerHour")
    public long getSpeedKilometersPerHour() {
        return speedKilometersPerHour;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SpeedTriggerDetailsObjectResponseBody
                && equalTo((SpeedTriggerDetailsObjectResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SpeedTriggerDetailsObjectResponseBody other) {
        return minDurationMilliseconds == other.minDurationMilliseconds
                && operation.equals(other.operation)
                && speedKilometersPerHour == other.speedKilometersPerHour;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.minDurationMilliseconds, this.operation, this.speedKilometersPerHour);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MinDurationMillisecondsStage builder() {
        return new Builder();
    }

    public interface MinDurationMillisecondsStage {
        /**
         * <p>The number of milliseconds the trigger needs to stay active before alerting.</p>
         */
        OperationStage minDurationMilliseconds(long minDurationMilliseconds);

        Builder from(SpeedTriggerDetailsObjectResponseBody other);
    }

    public interface OperationStage {
        /**
         * <p>How to evaluate the threshold.  Valid values: <code>GREATER</code>, <code>LESS</code></p>
         */
        SpeedKilometersPerHourStage operation(@NotNull SpeedTriggerDetailsObjectResponseBodyOperation operation);
    }

    public interface SpeedKilometersPerHourStage {
        /**
         * <p>The speed threshold value.</p>
         */
        _FinalStage speedKilometersPerHour(long speedKilometersPerHour);
    }

    public interface _FinalStage {
        SpeedTriggerDetailsObjectResponseBody build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements MinDurationMillisecondsStage, OperationStage, SpeedKilometersPerHourStage, _FinalStage {
        private long minDurationMilliseconds;

        private SpeedTriggerDetailsObjectResponseBodyOperation operation;

        private long speedKilometersPerHour;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SpeedTriggerDetailsObjectResponseBody other) {
            minDurationMilliseconds(other.getMinDurationMilliseconds());
            operation(other.getOperation());
            speedKilometersPerHour(other.getSpeedKilometersPerHour());
            return this;
        }

        /**
         * <p>The number of milliseconds the trigger needs to stay active before alerting.</p>
         * <p>The number of milliseconds the trigger needs to stay active before alerting.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("minDurationMilliseconds")
        public OperationStage minDurationMilliseconds(long minDurationMilliseconds) {
            this.minDurationMilliseconds = minDurationMilliseconds;
            return this;
        }

        /**
         * <p>How to evaluate the threshold.  Valid values: <code>GREATER</code>, <code>LESS</code></p>
         * <p>How to evaluate the threshold.  Valid values: <code>GREATER</code>, <code>LESS</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("operation")
        public SpeedKilometersPerHourStage operation(
                @NotNull SpeedTriggerDetailsObjectResponseBodyOperation operation) {
            this.operation = Objects.requireNonNull(operation, "operation must not be null");
            return this;
        }

        /**
         * <p>The speed threshold value.</p>
         * <p>The speed threshold value.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("speedKilometersPerHour")
        public _FinalStage speedKilometersPerHour(long speedKilometersPerHour) {
            this.speedKilometersPerHour = speedKilometersPerHour;
            return this;
        }

        @java.lang.Override
        public SpeedTriggerDetailsObjectResponseBody build() {
            return new SpeedTriggerDetailsObjectResponseBody(
                    minDurationMilliseconds, operation, speedKilometersPerHour, additionalProperties);
        }
    }
}
