/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TechnicianShiftObjectResponseBody.Builder.class)
public final class TechnicianShiftObjectResponseBody {
    private final OffsetDateTime clockInAtTime;

    private final TechnicianShiftObjectResponseBodyClockInSource clockInSource;

    private final Optional<OffsetDateTime> clockOutAtTime;

    private final Optional<TechnicianShiftObjectResponseBodyClockOutSource> clockOutSource;

    private final OffsetDateTime createdAtTime;

    private final Optional<String> driverId;

    private final Optional<Map<String, String>> externalIds;

    private final Optional<Map<String, String>> externalTechnicianIds;

    private final String id;

    private final Optional<String> placeId;

    private final TechnicianShiftObjectResponseBodyStatus status;

    private final OffsetDateTime updatedAtTime;

    private final Optional<String> userId;

    private final long version;

    private final Map<String, Object> additionalProperties;

    private TechnicianShiftObjectResponseBody(
            OffsetDateTime clockInAtTime,
            TechnicianShiftObjectResponseBodyClockInSource clockInSource,
            Optional<OffsetDateTime> clockOutAtTime,
            Optional<TechnicianShiftObjectResponseBodyClockOutSource> clockOutSource,
            OffsetDateTime createdAtTime,
            Optional<String> driverId,
            Optional<Map<String, String>> externalIds,
            Optional<Map<String, String>> externalTechnicianIds,
            String id,
            Optional<String> placeId,
            TechnicianShiftObjectResponseBodyStatus status,
            OffsetDateTime updatedAtTime,
            Optional<String> userId,
            long version,
            Map<String, Object> additionalProperties) {
        this.clockInAtTime = clockInAtTime;
        this.clockInSource = clockInSource;
        this.clockOutAtTime = clockOutAtTime;
        this.clockOutSource = clockOutSource;
        this.createdAtTime = createdAtTime;
        this.driverId = driverId;
        this.externalIds = externalIds;
        this.externalTechnicianIds = externalTechnicianIds;
        this.id = id;
        this.placeId = placeId;
        this.status = status;
        this.updatedAtTime = updatedAtTime;
        this.userId = userId;
        this.version = version;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Shift start.
     */
    @JsonProperty("clockInAtTime")
    public OffsetDateTime getClockInAtTime() {
        return clockInAtTime;
    }

    /**
     * @return Surface that recorded clock-in.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code>
     */
    @JsonProperty("clockInSource")
    public TechnicianShiftObjectResponseBodyClockInSource getClockInSource() {
        return clockInSource;
    }

    /**
     * @return Shift end; omitted while open.
     */
    @JsonProperty("clockOutAtTime")
    public Optional<OffsetDateTime> getClockOutAtTime() {
        return clockOutAtTime;
    }

    /**
     * @return Surface that recorded clock-out; omitted while open.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code>
     */
    @JsonProperty("clockOutSource")
    public Optional<TechnicianShiftObjectResponseBodyClockOutSource> getClockOutSource() {
        return clockOutSource;
    }

    /**
     * @return Server-recorded creation time.
     */
    @JsonProperty("createdAtTime")
    public OffsetDateTime getCreatedAtTime() {
        return createdAtTime;
    }

    /**
     * @return Linked Driver captured when the shift was created.
     */
    @JsonProperty("driverId")
    public Optional<String> getDriverId() {
        return driverId;
    }

    /**
     * @return External identifiers, with at most 30 pairs.
     */
    @JsonProperty("externalIds")
    public Optional<Map<String, String>> getExternalIds() {
        return externalIds;
    }

    /**
     * @return External identifiers, with at most 30 pairs.
     */
    @JsonProperty("externalTechnicianIds")
    public Optional<Map<String, String>> getExternalTechnicianIds() {
        return externalTechnicianIds;
    }

    /**
     * @return Stable server-generated shift UUID.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Maintenance-shop Place ID.
     */
    @JsonProperty("placeId")
    public Optional<String> getPlaceId() {
        return placeId;
    }

    /**
     * @return Derived shift status.  Valid values: <code>inProgress</code>, <code>completed</code>, <code>unknown</code>
     */
    @JsonProperty("status")
    public TechnicianShiftObjectResponseBodyStatus getStatus() {
        return status;
    }

    /**
     * @return Last material shift update.
     */
    @JsonProperty("updatedAtTime")
    public OffsetDateTime getUpdatedAtTime() {
        return updatedAtTime;
    }

    /**
     * @return Samsara User captured when the shift was created.
     */
    @JsonProperty("userId")
    public Optional<String> getUserId() {
        return userId;
    }

    /**
     * @return Server-managed revision. Echo the received value on PATCH.
     */
    @JsonProperty("version")
    public long getVersion() {
        return version;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TechnicianShiftObjectResponseBody && equalTo((TechnicianShiftObjectResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TechnicianShiftObjectResponseBody other) {
        return clockInAtTime.equals(other.clockInAtTime)
                && clockInSource.equals(other.clockInSource)
                && clockOutAtTime.equals(other.clockOutAtTime)
                && clockOutSource.equals(other.clockOutSource)
                && createdAtTime.equals(other.createdAtTime)
                && driverId.equals(other.driverId)
                && externalIds.equals(other.externalIds)
                && externalTechnicianIds.equals(other.externalTechnicianIds)
                && id.equals(other.id)
                && placeId.equals(other.placeId)
                && status.equals(other.status)
                && updatedAtTime.equals(other.updatedAtTime)
                && userId.equals(other.userId)
                && version == other.version;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.clockInAtTime,
                this.clockInSource,
                this.clockOutAtTime,
                this.clockOutSource,
                this.createdAtTime,
                this.driverId,
                this.externalIds,
                this.externalTechnicianIds,
                this.id,
                this.placeId,
                this.status,
                this.updatedAtTime,
                this.userId,
                this.version);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ClockInAtTimeStage builder() {
        return new Builder();
    }

    public interface ClockInAtTimeStage {
        /**
         * <p>Shift start.</p>
         */
        ClockInSourceStage clockInAtTime(@NotNull OffsetDateTime clockInAtTime);

        Builder from(TechnicianShiftObjectResponseBody other);
    }

    public interface ClockInSourceStage {
        /**
         * <p>Surface that recorded clock-in.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code></p>
         */
        CreatedAtTimeStage clockInSource(@NotNull TechnicianShiftObjectResponseBodyClockInSource clockInSource);
    }

    public interface CreatedAtTimeStage {
        /**
         * <p>Server-recorded creation time.</p>
         */
        IdStage createdAtTime(@NotNull OffsetDateTime createdAtTime);
    }

    public interface IdStage {
        /**
         * <p>Stable server-generated shift UUID.</p>
         */
        StatusStage id(@NotNull String id);
    }

    public interface StatusStage {
        /**
         * <p>Derived shift status.  Valid values: <code>inProgress</code>, <code>completed</code>, <code>unknown</code></p>
         */
        UpdatedAtTimeStage status(@NotNull TechnicianShiftObjectResponseBodyStatus status);
    }

    public interface UpdatedAtTimeStage {
        /**
         * <p>Last material shift update.</p>
         */
        VersionStage updatedAtTime(@NotNull OffsetDateTime updatedAtTime);
    }

    public interface VersionStage {
        /**
         * <p>Server-managed revision. Echo the received value on PATCH.</p>
         */
        _FinalStage version(long version);
    }

    public interface _FinalStage {
        TechnicianShiftObjectResponseBody build();

        /**
         * <p>Shift end; omitted while open.</p>
         */
        _FinalStage clockOutAtTime(Optional<OffsetDateTime> clockOutAtTime);

        _FinalStage clockOutAtTime(OffsetDateTime clockOutAtTime);

        /**
         * <p>Surface that recorded clock-out; omitted while open.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code></p>
         */
        _FinalStage clockOutSource(Optional<TechnicianShiftObjectResponseBodyClockOutSource> clockOutSource);

        _FinalStage clockOutSource(TechnicianShiftObjectResponseBodyClockOutSource clockOutSource);

        /**
         * <p>Linked Driver captured when the shift was created.</p>
         */
        _FinalStage driverId(Optional<String> driverId);

        _FinalStage driverId(String driverId);

        /**
         * <p>External identifiers, with at most 30 pairs.</p>
         */
        _FinalStage externalIds(Optional<Map<String, String>> externalIds);

        _FinalStage externalIds(Map<String, String> externalIds);

        /**
         * <p>External identifiers, with at most 30 pairs.</p>
         */
        _FinalStage externalTechnicianIds(Optional<Map<String, String>> externalTechnicianIds);

        _FinalStage externalTechnicianIds(Map<String, String> externalTechnicianIds);

        /**
         * <p>Maintenance-shop Place ID.</p>
         */
        _FinalStage placeId(Optional<String> placeId);

        _FinalStage placeId(String placeId);

        /**
         * <p>Samsara User captured when the shift was created.</p>
         */
        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ClockInAtTimeStage,
                    ClockInSourceStage,
                    CreatedAtTimeStage,
                    IdStage,
                    StatusStage,
                    UpdatedAtTimeStage,
                    VersionStage,
                    _FinalStage {
        private OffsetDateTime clockInAtTime;

        private TechnicianShiftObjectResponseBodyClockInSource clockInSource;

        private OffsetDateTime createdAtTime;

        private String id;

        private TechnicianShiftObjectResponseBodyStatus status;

        private OffsetDateTime updatedAtTime;

        private long version;

        private Optional<String> userId = Optional.empty();

        private Optional<String> placeId = Optional.empty();

        private Optional<Map<String, String>> externalTechnicianIds = Optional.empty();

        private Optional<Map<String, String>> externalIds = Optional.empty();

        private Optional<String> driverId = Optional.empty();

        private Optional<TechnicianShiftObjectResponseBodyClockOutSource> clockOutSource = Optional.empty();

        private Optional<OffsetDateTime> clockOutAtTime = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TechnicianShiftObjectResponseBody other) {
            clockInAtTime(other.getClockInAtTime());
            clockInSource(other.getClockInSource());
            clockOutAtTime(other.getClockOutAtTime());
            clockOutSource(other.getClockOutSource());
            createdAtTime(other.getCreatedAtTime());
            driverId(other.getDriverId());
            externalIds(other.getExternalIds());
            externalTechnicianIds(other.getExternalTechnicianIds());
            id(other.getId());
            placeId(other.getPlaceId());
            status(other.getStatus());
            updatedAtTime(other.getUpdatedAtTime());
            userId(other.getUserId());
            version(other.getVersion());
            return this;
        }

        /**
         * <p>Shift start.</p>
         * <p>Shift start.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("clockInAtTime")
        public ClockInSourceStage clockInAtTime(@NotNull OffsetDateTime clockInAtTime) {
            this.clockInAtTime = Objects.requireNonNull(clockInAtTime, "clockInAtTime must not be null");
            return this;
        }

        /**
         * <p>Surface that recorded clock-in.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code></p>
         * <p>Surface that recorded clock-in.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("clockInSource")
        public CreatedAtTimeStage clockInSource(@NotNull TechnicianShiftObjectResponseBodyClockInSource clockInSource) {
            this.clockInSource = Objects.requireNonNull(clockInSource, "clockInSource must not be null");
            return this;
        }

        /**
         * <p>Server-recorded creation time.</p>
         * <p>Server-recorded creation time.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAtTime")
        public IdStage createdAtTime(@NotNull OffsetDateTime createdAtTime) {
            this.createdAtTime = Objects.requireNonNull(createdAtTime, "createdAtTime must not be null");
            return this;
        }

        /**
         * <p>Stable server-generated shift UUID.</p>
         * <p>Stable server-generated shift UUID.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public StatusStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Derived shift status.  Valid values: <code>inProgress</code>, <code>completed</code>, <code>unknown</code></p>
         * <p>Derived shift status.  Valid values: <code>inProgress</code>, <code>completed</code>, <code>unknown</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public UpdatedAtTimeStage status(@NotNull TechnicianShiftObjectResponseBodyStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>Last material shift update.</p>
         * <p>Last material shift update.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updatedAtTime")
        public VersionStage updatedAtTime(@NotNull OffsetDateTime updatedAtTime) {
            this.updatedAtTime = Objects.requireNonNull(updatedAtTime, "updatedAtTime must not be null");
            return this;
        }

        /**
         * <p>Server-managed revision. Echo the received value on PATCH.</p>
         * <p>Server-managed revision. Echo the received value on PATCH.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("version")
        public _FinalStage version(long version) {
            this.version = version;
            return this;
        }

        /**
         * <p>Samsara User captured when the shift was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        /**
         * <p>Samsara User captured when the shift was created.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "userId", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        /**
         * <p>Maintenance-shop Place ID.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage placeId(String placeId) {
            this.placeId = Optional.ofNullable(placeId);
            return this;
        }

        /**
         * <p>Maintenance-shop Place ID.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "placeId", nulls = Nulls.SKIP)
        public _FinalStage placeId(Optional<String> placeId) {
            this.placeId = placeId;
            return this;
        }

        /**
         * <p>External identifiers, with at most 30 pairs.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalTechnicianIds(Map<String, String> externalTechnicianIds) {
            this.externalTechnicianIds = Optional.ofNullable(externalTechnicianIds);
            return this;
        }

        /**
         * <p>External identifiers, with at most 30 pairs.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "externalTechnicianIds", nulls = Nulls.SKIP)
        public _FinalStage externalTechnicianIds(Optional<Map<String, String>> externalTechnicianIds) {
            this.externalTechnicianIds = externalTechnicianIds;
            return this;
        }

        /**
         * <p>External identifiers, with at most 30 pairs.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalIds(Map<String, String> externalIds) {
            this.externalIds = Optional.ofNullable(externalIds);
            return this;
        }

        /**
         * <p>External identifiers, with at most 30 pairs.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "externalIds", nulls = Nulls.SKIP)
        public _FinalStage externalIds(Optional<Map<String, String>> externalIds) {
            this.externalIds = externalIds;
            return this;
        }

        /**
         * <p>Linked Driver captured when the shift was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage driverId(String driverId) {
            this.driverId = Optional.ofNullable(driverId);
            return this;
        }

        /**
         * <p>Linked Driver captured when the shift was created.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "driverId", nulls = Nulls.SKIP)
        public _FinalStage driverId(Optional<String> driverId) {
            this.driverId = driverId;
            return this;
        }

        /**
         * <p>Surface that recorded clock-out; omitted while open.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage clockOutSource(TechnicianShiftObjectResponseBodyClockOutSource clockOutSource) {
            this.clockOutSource = Optional.ofNullable(clockOutSource);
            return this;
        }

        /**
         * <p>Surface that recorded clock-out; omitted while open.  Valid values: <code>api</code>, <code>cloud</code>, <code>mobile</code>, <code>unknown</code></p>
         */
        @java.lang.Override
        @JsonSetter(value = "clockOutSource", nulls = Nulls.SKIP)
        public _FinalStage clockOutSource(Optional<TechnicianShiftObjectResponseBodyClockOutSource> clockOutSource) {
            this.clockOutSource = clockOutSource;
            return this;
        }

        /**
         * <p>Shift end; omitted while open.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage clockOutAtTime(OffsetDateTime clockOutAtTime) {
            this.clockOutAtTime = Optional.ofNullable(clockOutAtTime);
            return this;
        }

        /**
         * <p>Shift end; omitted while open.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "clockOutAtTime", nulls = Nulls.SKIP)
        public _FinalStage clockOutAtTime(Optional<OffsetDateTime> clockOutAtTime) {
            this.clockOutAtTime = clockOutAtTime;
            return this;
        }

        @java.lang.Override
        public TechnicianShiftObjectResponseBody build() {
            return new TechnicianShiftObjectResponseBody(
                    clockInAtTime,
                    clockInSource,
                    clockOutAtTime,
                    clockOutSource,
                    createdAtTime,
                    driverId,
                    externalIds,
                    externalTechnicianIds,
                    id,
                    placeId,
                    status,
                    updatedAtTime,
                    userId,
                    version,
                    additionalProperties);
        }
    }
}
