/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TrailerStatReeferDoorStateZone2TypeResponseBodyValue {
    public static final TrailerStatReeferDoorStateZone2TypeResponseBodyValue CLOSED =
            new TrailerStatReeferDoorStateZone2TypeResponseBodyValue(Value.CLOSED, "closed");

    public static final TrailerStatReeferDoorStateZone2TypeResponseBodyValue OPEN =
            new TrailerStatReeferDoorStateZone2TypeResponseBodyValue(Value.OPEN, "open");

    private final Value value;

    private final String string;

    TrailerStatReeferDoorStateZone2TypeResponseBodyValue(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TrailerStatReeferDoorStateZone2TypeResponseBodyValue
                        && this.string.equals(((TrailerStatReeferDoorStateZone2TypeResponseBodyValue) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CLOSED:
                return visitor.visitClosed();
            case OPEN:
                return visitor.visitOpen();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TrailerStatReeferDoorStateZone2TypeResponseBodyValue valueOf(String value) {
        switch (value) {
            case "closed":
                return CLOSED;
            case "open":
                return OPEN;
            default:
                return new TrailerStatReeferDoorStateZone2TypeResponseBodyValue(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OPEN,

        CLOSED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOpen();

        T visitClosed();

        T visitUnknown(String unknownType);
    }
}
