/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1VehicleHarshEventResponse.Builder.class)
public final class V1VehicleHarshEventResponse {
    private final Optional<String> downloadForwardVideoUrl;

    private final Optional<String> downloadInwardVideoUrl;

    private final Optional<String> downloadTrackedInwardVideoUrl;

    private final String harshEventType;

    private final String incidentReportUrl;

    private final Optional<Boolean> isDistracted;

    private final Optional<V1VehicleHarshEventResponseLocation> location;

    private final Map<String, Object> additionalProperties;

    private V1VehicleHarshEventResponse(
            Optional<String> downloadForwardVideoUrl,
            Optional<String> downloadInwardVideoUrl,
            Optional<String> downloadTrackedInwardVideoUrl,
            String harshEventType,
            String incidentReportUrl,
            Optional<Boolean> isDistracted,
            Optional<V1VehicleHarshEventResponseLocation> location,
            Map<String, Object> additionalProperties) {
        this.downloadForwardVideoUrl = downloadForwardVideoUrl;
        this.downloadInwardVideoUrl = downloadInwardVideoUrl;
        this.downloadTrackedInwardVideoUrl = downloadTrackedInwardVideoUrl;
        this.harshEventType = harshEventType;
        this.incidentReportUrl = incidentReportUrl;
        this.isDistracted = isDistracted;
        this.location = location;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return URL for downloading the forward facing video
     */
    @JsonProperty("downloadForwardVideoUrl")
    public Optional<String> getDownloadForwardVideoUrl() {
        return downloadForwardVideoUrl;
    }

    /**
     * @return URL for downloading the inward facing video
     */
    @JsonProperty("downloadInwardVideoUrl")
    public Optional<String> getDownloadInwardVideoUrl() {
        return downloadInwardVideoUrl;
    }

    /**
     * @return URL for downloading the tracked inward facing video
     */
    @JsonProperty("downloadTrackedInwardVideoUrl")
    public Optional<String> getDownloadTrackedInwardVideoUrl() {
        return downloadTrackedInwardVideoUrl;
    }

    /**
     * @return Type of the harsh event. One of: [Crash, Harsh Acceleration, Harsh Braking, Harsh Turn, ROP Engine, ROP Brake, YC Engine, YC Brake, Harsh Event]
     */
    @JsonProperty("harshEventType")
    public String getHarshEventType() {
        return harshEventType;
    }

    /**
     * @return URL of the associated incident report page
     */
    @JsonProperty("incidentReportUrl")
    public String getIncidentReportUrl() {
        return incidentReportUrl;
    }

    /**
     * @return Whether the driver was deemed distracted during this harsh event
     */
    @JsonProperty("isDistracted")
    public Optional<Boolean> getIsDistracted() {
        return isDistracted;
    }

    @JsonProperty("location")
    public Optional<V1VehicleHarshEventResponseLocation> getLocation() {
        return location;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1VehicleHarshEventResponse && equalTo((V1VehicleHarshEventResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1VehicleHarshEventResponse other) {
        return downloadForwardVideoUrl.equals(other.downloadForwardVideoUrl)
                && downloadInwardVideoUrl.equals(other.downloadInwardVideoUrl)
                && downloadTrackedInwardVideoUrl.equals(other.downloadTrackedInwardVideoUrl)
                && harshEventType.equals(other.harshEventType)
                && incidentReportUrl.equals(other.incidentReportUrl)
                && isDistracted.equals(other.isDistracted)
                && location.equals(other.location);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.downloadForwardVideoUrl,
                this.downloadInwardVideoUrl,
                this.downloadTrackedInwardVideoUrl,
                this.harshEventType,
                this.incidentReportUrl,
                this.isDistracted,
                this.location);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static HarshEventTypeStage builder() {
        return new Builder();
    }

    public interface HarshEventTypeStage {
        /**
         * <p>Type of the harsh event. One of: [Crash, Harsh Acceleration, Harsh Braking, Harsh Turn, ROP Engine, ROP Brake, YC Engine, YC Brake, Harsh Event]</p>
         */
        IncidentReportUrlStage harshEventType(@NotNull String harshEventType);

        Builder from(V1VehicleHarshEventResponse other);
    }

    public interface IncidentReportUrlStage {
        /**
         * <p>URL of the associated incident report page</p>
         */
        _FinalStage incidentReportUrl(@NotNull String incidentReportUrl);
    }

    public interface _FinalStage {
        V1VehicleHarshEventResponse build();

        /**
         * <p>URL for downloading the forward facing video</p>
         */
        _FinalStage downloadForwardVideoUrl(Optional<String> downloadForwardVideoUrl);

        _FinalStage downloadForwardVideoUrl(String downloadForwardVideoUrl);

        /**
         * <p>URL for downloading the inward facing video</p>
         */
        _FinalStage downloadInwardVideoUrl(Optional<String> downloadInwardVideoUrl);

        _FinalStage downloadInwardVideoUrl(String downloadInwardVideoUrl);

        /**
         * <p>URL for downloading the tracked inward facing video</p>
         */
        _FinalStage downloadTrackedInwardVideoUrl(Optional<String> downloadTrackedInwardVideoUrl);

        _FinalStage downloadTrackedInwardVideoUrl(String downloadTrackedInwardVideoUrl);

        /**
         * <p>Whether the driver was deemed distracted during this harsh event</p>
         */
        _FinalStage isDistracted(Optional<Boolean> isDistracted);

        _FinalStage isDistracted(Boolean isDistracted);

        _FinalStage location(Optional<V1VehicleHarshEventResponseLocation> location);

        _FinalStage location(V1VehicleHarshEventResponseLocation location);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements HarshEventTypeStage, IncidentReportUrlStage, _FinalStage {
        private String harshEventType;

        private String incidentReportUrl;

        private Optional<V1VehicleHarshEventResponseLocation> location = Optional.empty();

        private Optional<Boolean> isDistracted = Optional.empty();

        private Optional<String> downloadTrackedInwardVideoUrl = Optional.empty();

        private Optional<String> downloadInwardVideoUrl = Optional.empty();

        private Optional<String> downloadForwardVideoUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(V1VehicleHarshEventResponse other) {
            downloadForwardVideoUrl(other.getDownloadForwardVideoUrl());
            downloadInwardVideoUrl(other.getDownloadInwardVideoUrl());
            downloadTrackedInwardVideoUrl(other.getDownloadTrackedInwardVideoUrl());
            harshEventType(other.getHarshEventType());
            incidentReportUrl(other.getIncidentReportUrl());
            isDistracted(other.getIsDistracted());
            location(other.getLocation());
            return this;
        }

        /**
         * <p>Type of the harsh event. One of: [Crash, Harsh Acceleration, Harsh Braking, Harsh Turn, ROP Engine, ROP Brake, YC Engine, YC Brake, Harsh Event]</p>
         * <p>Type of the harsh event. One of: [Crash, Harsh Acceleration, Harsh Braking, Harsh Turn, ROP Engine, ROP Brake, YC Engine, YC Brake, Harsh Event]</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("harshEventType")
        public IncidentReportUrlStage harshEventType(@NotNull String harshEventType) {
            this.harshEventType = Objects.requireNonNull(harshEventType, "harshEventType must not be null");
            return this;
        }

        /**
         * <p>URL of the associated incident report page</p>
         * <p>URL of the associated incident report page</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("incidentReportUrl")
        public _FinalStage incidentReportUrl(@NotNull String incidentReportUrl) {
            this.incidentReportUrl = Objects.requireNonNull(incidentReportUrl, "incidentReportUrl must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage location(V1VehicleHarshEventResponseLocation location) {
            this.location = Optional.ofNullable(location);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "location", nulls = Nulls.SKIP)
        public _FinalStage location(Optional<V1VehicleHarshEventResponseLocation> location) {
            this.location = location;
            return this;
        }

        /**
         * <p>Whether the driver was deemed distracted during this harsh event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage isDistracted(Boolean isDistracted) {
            this.isDistracted = Optional.ofNullable(isDistracted);
            return this;
        }

        /**
         * <p>Whether the driver was deemed distracted during this harsh event</p>
         */
        @java.lang.Override
        @JsonSetter(value = "isDistracted", nulls = Nulls.SKIP)
        public _FinalStage isDistracted(Optional<Boolean> isDistracted) {
            this.isDistracted = isDistracted;
            return this;
        }

        /**
         * <p>URL for downloading the tracked inward facing video</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage downloadTrackedInwardVideoUrl(String downloadTrackedInwardVideoUrl) {
            this.downloadTrackedInwardVideoUrl = Optional.ofNullable(downloadTrackedInwardVideoUrl);
            return this;
        }

        /**
         * <p>URL for downloading the tracked inward facing video</p>
         */
        @java.lang.Override
        @JsonSetter(value = "downloadTrackedInwardVideoUrl", nulls = Nulls.SKIP)
        public _FinalStage downloadTrackedInwardVideoUrl(Optional<String> downloadTrackedInwardVideoUrl) {
            this.downloadTrackedInwardVideoUrl = downloadTrackedInwardVideoUrl;
            return this;
        }

        /**
         * <p>URL for downloading the inward facing video</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage downloadInwardVideoUrl(String downloadInwardVideoUrl) {
            this.downloadInwardVideoUrl = Optional.ofNullable(downloadInwardVideoUrl);
            return this;
        }

        /**
         * <p>URL for downloading the inward facing video</p>
         */
        @java.lang.Override
        @JsonSetter(value = "downloadInwardVideoUrl", nulls = Nulls.SKIP)
        public _FinalStage downloadInwardVideoUrl(Optional<String> downloadInwardVideoUrl) {
            this.downloadInwardVideoUrl = downloadInwardVideoUrl;
            return this;
        }

        /**
         * <p>URL for downloading the forward facing video</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage downloadForwardVideoUrl(String downloadForwardVideoUrl) {
            this.downloadForwardVideoUrl = Optional.ofNullable(downloadForwardVideoUrl);
            return this;
        }

        /**
         * <p>URL for downloading the forward facing video</p>
         */
        @java.lang.Override
        @JsonSetter(value = "downloadForwardVideoUrl", nulls = Nulls.SKIP)
        public _FinalStage downloadForwardVideoUrl(Optional<String> downloadForwardVideoUrl) {
            this.downloadForwardVideoUrl = downloadForwardVideoUrl;
            return this;
        }

        @java.lang.Override
        public V1VehicleHarshEventResponse build() {
            return new V1VehicleHarshEventResponse(
                    downloadForwardVideoUrl,
                    downloadInwardVideoUrl,
                    downloadTrackedInwardVideoUrl,
                    harshEventType,
                    incidentReportUrl,
                    isDistracted,
                    location,
                    additionalProperties);
        }
    }
}
