/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VehicleStatsDecorationsGps.Builder.class)
public final class VehicleStatsDecorationsGps {
    private final Optional<VehicleLocationAddress> address;

    private final Optional<Double> headingDegrees;

    private final Optional<Boolean> isEcuSpeed;

    private final double latitude;

    private final double longitude;

    private final Optional<ReverseGeo> reverseGeo;

    private final Optional<Double> speedMilesPerHour;

    private final Map<String, Object> additionalProperties;

    private VehicleStatsDecorationsGps(
            Optional<VehicleLocationAddress> address,
            Optional<Double> headingDegrees,
            Optional<Boolean> isEcuSpeed,
            double latitude,
            double longitude,
            Optional<ReverseGeo> reverseGeo,
            Optional<Double> speedMilesPerHour,
            Map<String, Object> additionalProperties) {
        this.address = address;
        this.headingDegrees = headingDegrees;
        this.isEcuSpeed = isEcuSpeed;
        this.latitude = latitude;
        this.longitude = longitude;
        this.reverseGeo = reverseGeo;
        this.speedMilesPerHour = speedMilesPerHour;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("address")
    public Optional<VehicleLocationAddress> getAddress() {
        return address;
    }

    @JsonProperty("headingDegrees")
    public Optional<Double> getHeadingDegrees() {
        return headingDegrees;
    }

    @JsonProperty("isEcuSpeed")
    public Optional<Boolean> getIsEcuSpeed() {
        return isEcuSpeed;
    }

    @JsonProperty("latitude")
    public double getLatitude() {
        return latitude;
    }

    @JsonProperty("longitude")
    public double getLongitude() {
        return longitude;
    }

    @JsonProperty("reverseGeo")
    public Optional<ReverseGeo> getReverseGeo() {
        return reverseGeo;
    }

    @JsonProperty("speedMilesPerHour")
    public Optional<Double> getSpeedMilesPerHour() {
        return speedMilesPerHour;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VehicleStatsDecorationsGps && equalTo((VehicleStatsDecorationsGps) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VehicleStatsDecorationsGps other) {
        return address.equals(other.address)
                && headingDegrees.equals(other.headingDegrees)
                && isEcuSpeed.equals(other.isEcuSpeed)
                && latitude == other.latitude
                && longitude == other.longitude
                && reverseGeo.equals(other.reverseGeo)
                && speedMilesPerHour.equals(other.speedMilesPerHour);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.address,
                this.headingDegrees,
                this.isEcuSpeed,
                this.latitude,
                this.longitude,
                this.reverseGeo,
                this.speedMilesPerHour);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static LatitudeStage builder() {
        return new Builder();
    }

    public interface LatitudeStage {
        LongitudeStage latitude(double latitude);

        Builder from(VehicleStatsDecorationsGps other);
    }

    public interface LongitudeStage {
        _FinalStage longitude(double longitude);
    }

    public interface _FinalStage {
        VehicleStatsDecorationsGps build();

        _FinalStage address(Optional<VehicleLocationAddress> address);

        _FinalStage address(VehicleLocationAddress address);

        _FinalStage headingDegrees(Optional<Double> headingDegrees);

        _FinalStage headingDegrees(Double headingDegrees);

        _FinalStage isEcuSpeed(Optional<Boolean> isEcuSpeed);

        _FinalStage isEcuSpeed(Boolean isEcuSpeed);

        _FinalStage reverseGeo(Optional<ReverseGeo> reverseGeo);

        _FinalStage reverseGeo(ReverseGeo reverseGeo);

        _FinalStage speedMilesPerHour(Optional<Double> speedMilesPerHour);

        _FinalStage speedMilesPerHour(Double speedMilesPerHour);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements LatitudeStage, LongitudeStage, _FinalStage {
        private double latitude;

        private double longitude;

        private Optional<Double> speedMilesPerHour = Optional.empty();

        private Optional<ReverseGeo> reverseGeo = Optional.empty();

        private Optional<Boolean> isEcuSpeed = Optional.empty();

        private Optional<Double> headingDegrees = Optional.empty();

        private Optional<VehicleLocationAddress> address = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(VehicleStatsDecorationsGps other) {
            address(other.getAddress());
            headingDegrees(other.getHeadingDegrees());
            isEcuSpeed(other.getIsEcuSpeed());
            latitude(other.getLatitude());
            longitude(other.getLongitude());
            reverseGeo(other.getReverseGeo());
            speedMilesPerHour(other.getSpeedMilesPerHour());
            return this;
        }

        @java.lang.Override
        @JsonSetter("latitude")
        public LongitudeStage latitude(double latitude) {
            this.latitude = latitude;
            return this;
        }

        @java.lang.Override
        @JsonSetter("longitude")
        public _FinalStage longitude(double longitude) {
            this.longitude = longitude;
            return this;
        }

        @java.lang.Override
        public _FinalStage speedMilesPerHour(Double speedMilesPerHour) {
            this.speedMilesPerHour = Optional.ofNullable(speedMilesPerHour);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "speedMilesPerHour", nulls = Nulls.SKIP)
        public _FinalStage speedMilesPerHour(Optional<Double> speedMilesPerHour) {
            this.speedMilesPerHour = speedMilesPerHour;
            return this;
        }

        @java.lang.Override
        public _FinalStage reverseGeo(ReverseGeo reverseGeo) {
            this.reverseGeo = Optional.ofNullable(reverseGeo);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "reverseGeo", nulls = Nulls.SKIP)
        public _FinalStage reverseGeo(Optional<ReverseGeo> reverseGeo) {
            this.reverseGeo = reverseGeo;
            return this;
        }

        @java.lang.Override
        public _FinalStage isEcuSpeed(Boolean isEcuSpeed) {
            this.isEcuSpeed = Optional.ofNullable(isEcuSpeed);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "isEcuSpeed", nulls = Nulls.SKIP)
        public _FinalStage isEcuSpeed(Optional<Boolean> isEcuSpeed) {
            this.isEcuSpeed = isEcuSpeed;
            return this;
        }

        @java.lang.Override
        public _FinalStage headingDegrees(Double headingDegrees) {
            this.headingDegrees = Optional.ofNullable(headingDegrees);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "headingDegrees", nulls = Nulls.SKIP)
        public _FinalStage headingDegrees(Optional<Double> headingDegrees) {
            this.headingDegrees = headingDegrees;
            return this;
        }

        @java.lang.Override
        public _FinalStage address(VehicleLocationAddress address) {
            this.address = Optional.ofNullable(address);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "address", nulls = Nulls.SKIP)
        public _FinalStage address(Optional<VehicleLocationAddress> address) {
            this.address = address;
            return this;
        }

        @java.lang.Override
        public VehicleStatsDecorationsGps build() {
            return new VehicleStatsDecorationsGps(
                    address,
                    headingDegrees,
                    isEcuSpeed,
                    latitude,
                    longitude,
                    reverseGeo,
                    speedMilesPerHour,
                    additionalProperties);
        }
    }
}
