/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VehicleDetectedResponseBody.Builder.class)
public final class VehicleDetectedResponseBody {
    private final Optional<AlertObjectOnvifCameraStreamResponseBody> cameraStream;

    private final Map<String, Object> additionalProperties;

    private VehicleDetectedResponseBody(
            Optional<AlertObjectOnvifCameraStreamResponseBody> cameraStream, Map<String, Object> additionalProperties) {
        this.cameraStream = cameraStream;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("cameraStream")
    public Optional<AlertObjectOnvifCameraStreamResponseBody> getCameraStream() {
        return cameraStream;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VehicleDetectedResponseBody && equalTo((VehicleDetectedResponseBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VehicleDetectedResponseBody other) {
        return cameraStream.equals(other.cameraStream);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.cameraStream);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<AlertObjectOnvifCameraStreamResponseBody> cameraStream = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(VehicleDetectedResponseBody other) {
            cameraStream(other.getCameraStream());
            return this;
        }

        @JsonSetter(value = "cameraStream", nulls = Nulls.SKIP)
        public Builder cameraStream(Optional<AlertObjectOnvifCameraStreamResponseBody> cameraStream) {
            this.cameraStream = cameraStream;
            return this;
        }

        public Builder cameraStream(AlertObjectOnvifCameraStreamResponseBody cameraStream) {
            this.cameraStream = Optional.ofNullable(cameraStream);
            return this;
        }

        public VehicleDetectedResponseBody build() {
            return new VehicleDetectedResponseBody(cameraStream, additionalProperties);
        }
    }
}
