/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.legacyapis;

import com.samsara.api.core.ClientOptions;
import com.samsara.api.core.RequestOptions;
import com.samsara.api.resources.legacyapis.requests.GetDriversVehicleAssignmentsRequest;
import com.samsara.api.resources.legacyapis.requests.GetDvirDefectsRequest;
import com.samsara.api.resources.legacyapis.requests.GetDvirHistoryRequest;
import com.samsara.api.resources.legacyapis.requests.GetSafetyActivityEventFeedRequest;
import com.samsara.api.resources.legacyapis.requests.GetSafetyEventsRequest;
import com.samsara.api.resources.legacyapis.requests.GetVehicleIdlingReportsRequest;
import com.samsara.api.resources.legacyapis.requests.GetVehiclesDriverAssignmentsRequest;
import com.samsara.api.resources.legacyapis.requests.V1GetVehicleHarshEventRequest;
import com.samsara.api.types.DefectsResponse;
import com.samsara.api.types.DriversVehicleAssignmentsGetDriversVehicleAssignmentsResponseBody;
import com.samsara.api.types.DvirsListResponse;
import com.samsara.api.types.IdlingReportsGetVehicleIdlingReportsResponseBody;
import com.samsara.api.types.SafetyEventsGetSafetyActivityEventFeedResponseBody;
import com.samsara.api.types.SafetyEventsListResponse;
import com.samsara.api.types.V1VehicleHarshEventResponse;
import com.samsara.api.types.VehiclesDriverAssignmentsGetVehiclesDriverAssignmentsResponseBody;
import java.util.concurrent.CompletableFuture;

public class AsyncLegacyApIsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawLegacyApIsClient rawClient;

    public AsyncLegacyApIsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawLegacyApIsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawLegacyApIsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/streamdefects">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Returns a list of DVIR defects in an organization, filtered by creation time. The maximum time period you can query for is 30 days.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Defects</strong> under the Maintenance category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<DefectsResponse> getDvirDefects(GetDvirDefectsRequest request) {
        return this.rawClient.getDvirDefects(request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/streamdefects">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Returns a list of DVIR defects in an organization, filtered by creation time. The maximum time period you can query for is 30 days.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Defects</strong> under the Maintenance category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<DefectsResponse> getDvirDefects(
            GetDvirDefectsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getDvirDefects(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all vehicle assignments for the requested drivers in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 25 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<DriversVehicleAssignmentsGetDriversVehicleAssignmentsResponseBody>
            getDriversVehicleAssignments() {
        return this.rawClient.getDriversVehicleAssignments().thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all vehicle assignments for the requested drivers in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 25 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<DriversVehicleAssignmentsGetDriversVehicleAssignmentsResponseBody>
            getDriversVehicleAssignments(RequestOptions requestOptions) {
        return this.rawClient.getDriversVehicleAssignments(requestOptions).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all vehicle assignments for the requested drivers in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 25 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<DriversVehicleAssignmentsGetDriversVehicleAssignmentsResponseBody>
            getDriversVehicleAssignments(GetDriversVehicleAssignmentsRequest request) {
        return this.rawClient.getDriversVehicleAssignments(request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all vehicle assignments for the requested drivers in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 25 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<DriversVehicleAssignmentsGetDriversVehicleAssignmentsResponseBody>
            getDriversVehicleAssignments(GetDriversVehicleAssignmentsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getDriversVehicleAssignments(request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdvirs">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Returns a list of all DVIRs in an organization.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read DVIRs</strong> under the Maintenance category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<DvirsListResponse> getDvirHistory(GetDvirHistoryRequest request) {
        return this.rawClient.getDvirHistory(request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdvirs">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Returns a list of all DVIRs in an organization.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read DVIRs</strong> under the Maintenance category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<DvirsListResponse> getDvirHistory(
            GetDvirHistoryRequest request, RequestOptions requestOptions) {
        return this.rawClient.getDvirHistory(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getidlingevents">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all vehicle idling reports for the requested time duration.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 25 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Fuel &amp; Energy</strong> under the Fuel &amp; Energy category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<IdlingReportsGetVehicleIdlingReportsResponseBody> getVehicleIdlingReports(
            GetVehicleIdlingReportsRequest request) {
        return this.rawClient.getVehicleIdlingReports(request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getidlingevents">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all vehicle idling reports for the requested time duration.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 25 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Fuel &amp; Energy</strong> under the Fuel &amp; Energy category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<IdlingReportsGetVehicleIdlingReportsResponseBody> getVehicleIdlingReports(
            GetVehicleIdlingReportsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getVehicleIdlingReports(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Fetch safety events for the organization in a given time period.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<SafetyEventsListResponse> getSafetyEvents(GetSafetyEventsRequest request) {
        return this.rawClient.getSafetyEvents(request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Fetch safety events for the organization in a given time period.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<SafetyEventsListResponse> getSafetyEvents(
            GetSafetyEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getSafetyEvents(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Get continuous safety events. The safety activity event feed offers a change-log for safety events. Use this endpoint to subscribe to safety event changes. See documentation below for all supported change-log types.</p>
     * <p>| ActivityType      | Description |
     * | ----------- | ----------- |
     * | CreateSafetyEventActivityType | a new safety event is processed by Samsara      |
     * | BehaviorLabelActivityType     | a label is added or removed from a safety event |
     * | CoachingStateActivityType     | a safety event coaching state is updated        |</p>
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<SafetyEventsGetSafetyActivityEventFeedResponseBody> getSafetyActivityEventFeed() {
        return this.rawClient.getSafetyActivityEventFeed().thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Get continuous safety events. The safety activity event feed offers a change-log for safety events. Use this endpoint to subscribe to safety event changes. See documentation below for all supported change-log types.</p>
     * <p>| ActivityType      | Description |
     * | ----------- | ----------- |
     * | CreateSafetyEventActivityType | a new safety event is processed by Samsara      |
     * | BehaviorLabelActivityType     | a label is added or removed from a safety event |
     * | CoachingStateActivityType     | a safety event coaching state is updated        |</p>
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<SafetyEventsGetSafetyActivityEventFeedResponseBody> getSafetyActivityEventFeed(
            RequestOptions requestOptions) {
        return this.rawClient.getSafetyActivityEventFeed(requestOptions).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Get continuous safety events. The safety activity event feed offers a change-log for safety events. Use this endpoint to subscribe to safety event changes. See documentation below for all supported change-log types.</p>
     * <p>| ActivityType      | Description |
     * | ----------- | ----------- |
     * | CreateSafetyEventActivityType | a new safety event is processed by Samsara      |
     * | BehaviorLabelActivityType     | a label is added or removed from a safety event |
     * | CoachingStateActivityType     | a safety event coaching state is updated        |</p>
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<SafetyEventsGetSafetyActivityEventFeedResponseBody> getSafetyActivityEventFeed(
            GetSafetyActivityEventFeedRequest request) {
        return this.rawClient.getSafetyActivityEventFeed(request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong>
     * <p>Get continuous safety events. The safety activity event feed offers a change-log for safety events. Use this endpoint to subscribe to safety event changes. See documentation below for all supported change-log types.</p>
     * <p>| ActivityType      | Description |
     * | ----------- | ----------- |
     * | CreateSafetyEventActivityType | a new safety event is processed by Samsara      |
     * | BehaviorLabelActivityType     | a label is added or removed from a safety event |
     * | CoachingStateActivityType     | a safety event coaching state is updated        |</p>
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<SafetyEventsGetSafetyActivityEventFeedResponseBody> getSafetyActivityEventFeed(
            GetSafetyActivityEventFeedRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getSafetyActivityEventFeed(request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all driver assignments for the requested vehicles in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<VehiclesDriverAssignmentsGetVehiclesDriverAssignmentsResponseBody>
            getVehiclesDriverAssignments() {
        return this.rawClient.getVehiclesDriverAssignments().thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all driver assignments for the requested vehicles in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<VehiclesDriverAssignmentsGetVehiclesDriverAssignmentsResponseBody>
            getVehiclesDriverAssignments(RequestOptions requestOptions) {
        return this.rawClient.getVehiclesDriverAssignments(requestOptions).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all driver assignments for the requested vehicles in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<VehiclesDriverAssignmentsGetVehiclesDriverAssignmentsResponseBody>
            getVehiclesDriverAssignments(GetVehiclesDriverAssignmentsRequest request) {
        return this.rawClient.getVehiclesDriverAssignments(request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getdrivervehicleassignments">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> Get all driver assignments for the requested vehicles in the requested time range. The only type of assignment supported right now are assignments created through the driver app.
     * <p>&lt;b&gt;Rate limit:&lt;/b&gt; 5 requests/sec (learn more about rate limits &lt;a href=&quot;https://developers.samsara.com/docs/rate-limits&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;).</p>
     * <p>To use this endpoint, select <strong>Read Assignments</strong> under the Assignments category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     */
    public CompletableFuture<VehiclesDriverAssignmentsGetVehiclesDriverAssignmentsResponseBody>
            getVehiclesDriverAssignments(GetVehiclesDriverAssignmentsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getVehiclesDriverAssignments(request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> &lt;n class=&quot;warning&quot;&gt;
     * &lt;nh&gt;
     * &lt;i class=&quot;fa fa-exclamation-circle&quot;&gt;&lt;/i&gt;
     * This endpoint is still on our legacy API.
     * &lt;/nh&gt;
     * &lt;/n&gt;
     * <p>Fetch harsh event details for a vehicle.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<V1VehicleHarshEventResponse> v1GetVehicleHarshEvent(
            long vehicleId, V1GetVehicleHarshEventRequest request) {
        return this.rawClient.v1GetVehicleHarshEvent(vehicleId, request).thenApply(response -> response.body());
    }

    /**
     * <strong>Note: This is a legacy endpoint, consider using <a href="https://developers.samsara.com/reference/getsafetyeventsv2stream">this endpoint</a> instead. The endpoint will continue to function as documented.</strong> &lt;n class=&quot;warning&quot;&gt;
     * &lt;nh&gt;
     * &lt;i class=&quot;fa fa-exclamation-circle&quot;&gt;&lt;/i&gt;
     * This endpoint is still on our legacy API.
     * &lt;/nh&gt;
     * &lt;/n&gt;
     * <p>Fetch harsh event details for a vehicle.</p>
     * <p><strong>Submit Feedback</strong>: Likes, dislikes, and API feature requests should be filed as feedback in our &lt;a href=&quot;https://forms.gle/zkD4NCH7HjKb7mm69&quot; target=&quot;_blank&quot;&gt;API feedback form&lt;/a&gt;. If you encountered an issue or noticed inaccuracies in the API documentation, please &lt;a href=&quot;https://www.samsara.com/help&quot; target=&quot;_blank&quot;&gt;submit a case&lt;/a&gt; to our support team.</p>
     * <p>To use this endpoint, select <strong>Read Safety Events &amp; Scores</strong> under the Safety &amp; Cameras category when creating or editing an API token. &lt;a href=&quot;https://developers.samsara.com/docs/authentication#scopes-for-api-tokens&quot; target=&quot;_blank&quot;&gt;Learn More.&lt;/a&gt;</p>
     */
    public CompletableFuture<V1VehicleHarshEventResponse> v1GetVehicleHarshEvent(
            long vehicleId, V1GetVehicleHarshEventRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .v1GetVehicleHarshEvent(vehicleId, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
