/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.betaapis.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import com.samsara.api.resources.betaapis.types.EntityWatchpointsServiceCreateWatchpointRequestBodyMode;
import com.samsara.api.resources.betaapis.types.EntityWatchpointsServiceCreateWatchpointRequestBodyObservationType;
import com.samsara.api.types.WatchpointLatLngTypeRequestBody;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EntityWatchpointsServiceCreateWatchpointRequestBody.Builder.class)
public final class EntityWatchpointsServiceCreateWatchpointRequestBody {
    private final WatchpointLatLngTypeRequestBody location;

    private final EntityWatchpointsServiceCreateWatchpointRequestBodyMode mode;

    private final Optional<String> name;

    private final Optional<String> note;

    private final EntityWatchpointsServiceCreateWatchpointRequestBodyObservationType observationType;

    private final Map<String, Object> additionalProperties;

    private EntityWatchpointsServiceCreateWatchpointRequestBody(
            WatchpointLatLngTypeRequestBody location,
            EntityWatchpointsServiceCreateWatchpointRequestBodyMode mode,
            Optional<String> name,
            Optional<String> note,
            EntityWatchpointsServiceCreateWatchpointRequestBodyObservationType observationType,
            Map<String, Object> additionalProperties) {
        this.location = location;
        this.mode = mode;
        this.name = name;
        this.note = note;
        this.observationType = observationType;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("location")
    public WatchpointLatLngTypeRequestBody getLocation() {
        return location;
    }

    /**
     * @return Recurrence frequency for observations.  Valid values: <code>justOnce</code>, <code>daily</code>, <code>weekly</code>, <code>monthly</code>
     */
    @JsonProperty("mode")
    public EntityWatchpointsServiceCreateWatchpointRequestBodyMode getMode() {
        return mode;
    }

    /**
     * @return Customer-provided name for the watchpoint.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Customer-provided note about the watchpoint.
     */
    @JsonProperty("note")
    public Optional<String> getNote() {
        return note;
    }

    /**
     * @return Type of condition to observe at this watchpoint.  Valid values: <code>roadDefect</code>, <code>utilityCut</code>, <code>guardrail</code>, <code>streetlight</code>, <code>signage</code>, <code>stormDrain</code>, <code>graffiti</code>, <code>vegetation</code>, <code>blight</code>, <code>illegalDumping</code>, <code>littering</code>, <code>highVegetationWeeds</code>, <code>fire</code>, <code>other</code>
     */
    @JsonProperty("observationType")
    public EntityWatchpointsServiceCreateWatchpointRequestBodyObservationType getObservationType() {
        return observationType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EntityWatchpointsServiceCreateWatchpointRequestBody
                && equalTo((EntityWatchpointsServiceCreateWatchpointRequestBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EntityWatchpointsServiceCreateWatchpointRequestBody other) {
        return location.equals(other.location)
                && mode.equals(other.mode)
                && name.equals(other.name)
                && note.equals(other.note)
                && observationType.equals(other.observationType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.location, this.mode, this.name, this.note, this.observationType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static LocationStage builder() {
        return new Builder();
    }

    public interface LocationStage {
        ModeStage location(@NotNull WatchpointLatLngTypeRequestBody location);

        Builder from(EntityWatchpointsServiceCreateWatchpointRequestBody other);
    }

    public interface ModeStage {
        /**
         * <p>Recurrence frequency for observations.  Valid values: <code>justOnce</code>, <code>daily</code>, <code>weekly</code>, <code>monthly</code></p>
         */
        ObservationTypeStage mode(@NotNull EntityWatchpointsServiceCreateWatchpointRequestBodyMode mode);
    }

    public interface ObservationTypeStage {
        /**
         * <p>Type of condition to observe at this watchpoint.  Valid values: <code>roadDefect</code>, <code>utilityCut</code>, <code>guardrail</code>, <code>streetlight</code>, <code>signage</code>, <code>stormDrain</code>, <code>graffiti</code>, <code>vegetation</code>, <code>blight</code>, <code>illegalDumping</code>, <code>littering</code>, <code>highVegetationWeeds</code>, <code>fire</code>, <code>other</code></p>
         */
        _FinalStage observationType(
                @NotNull EntityWatchpointsServiceCreateWatchpointRequestBodyObservationType observationType);
    }

    public interface _FinalStage {
        EntityWatchpointsServiceCreateWatchpointRequestBody build();

        /**
         * <p>Customer-provided name for the watchpoint.</p>
         */
        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        /**
         * <p>Customer-provided note about the watchpoint.</p>
         */
        _FinalStage note(Optional<String> note);

        _FinalStage note(String note);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements LocationStage, ModeStage, ObservationTypeStage, _FinalStage {
        private WatchpointLatLngTypeRequestBody location;

        private EntityWatchpointsServiceCreateWatchpointRequestBodyMode mode;

        private EntityWatchpointsServiceCreateWatchpointRequestBodyObservationType observationType;

        private Optional<String> note = Optional.empty();

        private Optional<String> name = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EntityWatchpointsServiceCreateWatchpointRequestBody other) {
            location(other.getLocation());
            mode(other.getMode());
            name(other.getName());
            note(other.getNote());
            observationType(other.getObservationType());
            return this;
        }

        @java.lang.Override
        @JsonSetter("location")
        public ModeStage location(@NotNull WatchpointLatLngTypeRequestBody location) {
            this.location = Objects.requireNonNull(location, "location must not be null");
            return this;
        }

        /**
         * <p>Recurrence frequency for observations.  Valid values: <code>justOnce</code>, <code>daily</code>, <code>weekly</code>, <code>monthly</code></p>
         * <p>Recurrence frequency for observations.  Valid values: <code>justOnce</code>, <code>daily</code>, <code>weekly</code>, <code>monthly</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("mode")
        public ObservationTypeStage mode(@NotNull EntityWatchpointsServiceCreateWatchpointRequestBodyMode mode) {
            this.mode = Objects.requireNonNull(mode, "mode must not be null");
            return this;
        }

        /**
         * <p>Type of condition to observe at this watchpoint.  Valid values: <code>roadDefect</code>, <code>utilityCut</code>, <code>guardrail</code>, <code>streetlight</code>, <code>signage</code>, <code>stormDrain</code>, <code>graffiti</code>, <code>vegetation</code>, <code>blight</code>, <code>illegalDumping</code>, <code>littering</code>, <code>highVegetationWeeds</code>, <code>fire</code>, <code>other</code></p>
         * <p>Type of condition to observe at this watchpoint.  Valid values: <code>roadDefect</code>, <code>utilityCut</code>, <code>guardrail</code>, <code>streetlight</code>, <code>signage</code>, <code>stormDrain</code>, <code>graffiti</code>, <code>vegetation</code>, <code>blight</code>, <code>illegalDumping</code>, <code>littering</code>, <code>highVegetationWeeds</code>, <code>fire</code>, <code>other</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("observationType")
        public _FinalStage observationType(
                @NotNull EntityWatchpointsServiceCreateWatchpointRequestBodyObservationType observationType) {
            this.observationType = Objects.requireNonNull(observationType, "observationType must not be null");
            return this;
        }

        /**
         * <p>Customer-provided note about the watchpoint.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage note(String note) {
            this.note = Optional.ofNullable(note);
            return this;
        }

        /**
         * <p>Customer-provided note about the watchpoint.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "note", nulls = Nulls.SKIP)
        public _FinalStage note(Optional<String> note) {
            this.note = note;
            return this;
        }

        /**
         * <p>Customer-provided name for the watchpoint.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Customer-provided name for the watchpoint.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        public EntityWatchpointsServiceCreateWatchpointRequestBody build() {
            return new EntityWatchpointsServiceCreateWatchpointRequestBody(
                    location, mode, name, note, observationType, additionalProperties);
        }
    }
}
