/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.betaapis.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetReadingsHistoryRequest.Builder.class)
public final class GetReadingsHistoryRequest {
    private final Optional<String> after;

    private final String readingId;

    private final Optional<String> entityIds;

    private final String entityType;

    private final Optional<String> externalIds;

    private final Optional<String> startTime;

    private final Optional<String> endTime;

    private final Optional<Boolean> feed;

    private final Optional<Boolean> includeExternalIds;

    private final Map<String, Object> additionalProperties;

    private GetReadingsHistoryRequest(
            Optional<String> after,
            String readingId,
            Optional<String> entityIds,
            String entityType,
            Optional<String> externalIds,
            Optional<String> startTime,
            Optional<String> endTime,
            Optional<Boolean> feed,
            Optional<Boolean> includeExternalIds,
            Map<String, Object> additionalProperties) {
        this.after = after;
        this.readingId = readingId;
        this.entityIds = entityIds;
        this.entityType = entityType;
        this.externalIds = externalIds;
        this.startTime = startTime;
        this.endTime = endTime;
        this.feed = feed;
        this.includeExternalIds = includeExternalIds;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.
     */
    @JsonProperty("after")
    public Optional<String> getAfter() {
        return after;
    }

    /**
     * @return The reading ID to retrieve data for. Use /readings/definitions endpoint to get a list of valid reading IDs. (Examples: engineRpm,fuelLevel)
     */
    @JsonProperty("readingId")
    public String getReadingId() {
        return readingId;
    }

    /**
     * @return A filter on the data based on this comma-separated list of entity IDs or external IDs. If not set, all entities are returned.
     */
    @JsonProperty("entityIds")
    public Optional<String> getEntityIds() {
        return entityIds;
    }

    /**
     * @return A entity type of the entityIds or externalIds to fetch readings for. Use /readings/definitions endpoint to get a list of valid entity types. (Examples: asset, sensor)
     */
    @JsonProperty("entityType")
    public String getEntityType() {
        return entityType;
    }

    /**
     * @return A filter on the data based on this comma-separated list of external IDs. (Examples: samsara.serial:ZPXKLMN7VJ, samsara.serial:ABXKIMN4NM)
     */
    @JsonProperty("externalIds")
    public Optional<String> getExternalIds() {
        return externalIds;
    }

    /**
     * @return A filter on the data that returns the last known data points with timestamps greater than or equal to this value. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)
     */
    @JsonProperty("startTime")
    public Optional<String> getStartTime() {
        return startTime;
    }

    /**
     * @return A filter on the data that returns the last known data points with timestamps less than or equal to this value. If not set, the time of the request is considered the endTime. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)
     */
    @JsonProperty("endTime")
    public Optional<String> getEndTime() {
        return endTime;
    }

    /**
     * @return Set to true to enable feed mode for continuous reading updates. When enabled, the API always includes an endCursor in the response. If hasNextPage is false, it indicates that no new data is currently available — wait at least 5 seconds before making the next request to avoid unnecessary polling.
     */
    @JsonProperty("feed")
    public Optional<Boolean> getFeed() {
        return feed;
    }

    /**
     * @return Optional boolean indicating whether to return external IDs on supported entities
     */
    @JsonProperty("includeExternalIds")
    public Optional<Boolean> getIncludeExternalIds() {
        return includeExternalIds;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetReadingsHistoryRequest && equalTo((GetReadingsHistoryRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetReadingsHistoryRequest other) {
        return after.equals(other.after)
                && readingId.equals(other.readingId)
                && entityIds.equals(other.entityIds)
                && entityType.equals(other.entityType)
                && externalIds.equals(other.externalIds)
                && startTime.equals(other.startTime)
                && endTime.equals(other.endTime)
                && feed.equals(other.feed)
                && includeExternalIds.equals(other.includeExternalIds);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.after,
                this.readingId,
                this.entityIds,
                this.entityType,
                this.externalIds,
                this.startTime,
                this.endTime,
                this.feed,
                this.includeExternalIds);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReadingIdStage builder() {
        return new Builder();
    }

    public interface ReadingIdStage {
        /**
         * <p>The reading ID to retrieve data for. Use /readings/definitions endpoint to get a list of valid reading IDs. (Examples: engineRpm,fuelLevel)</p>
         */
        EntityTypeStage readingId(@NotNull String readingId);

        Builder from(GetReadingsHistoryRequest other);
    }

    public interface EntityTypeStage {
        /**
         * <p>A entity type of the entityIds or externalIds to fetch readings for. Use /readings/definitions endpoint to get a list of valid entity types. (Examples: asset, sensor)</p>
         */
        _FinalStage entityType(@NotNull String entityType);
    }

    public interface _FinalStage {
        GetReadingsHistoryRequest build();

        /**
         * <p>If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.</p>
         */
        _FinalStage after(Optional<String> after);

        _FinalStage after(String after);

        /**
         * <p>A filter on the data based on this comma-separated list of entity IDs or external IDs. If not set, all entities are returned.</p>
         */
        _FinalStage entityIds(Optional<String> entityIds);

        _FinalStage entityIds(String entityIds);

        /**
         * <p>A filter on the data based on this comma-separated list of external IDs. (Examples: samsara.serial:ZPXKLMN7VJ, samsara.serial:ABXKIMN4NM)</p>
         */
        _FinalStage externalIds(Optional<String> externalIds);

        _FinalStage externalIds(String externalIds);

        /**
         * <p>A filter on the data that returns the last known data points with timestamps greater than or equal to this value. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)</p>
         */
        _FinalStage startTime(Optional<String> startTime);

        _FinalStage startTime(String startTime);

        /**
         * <p>A filter on the data that returns the last known data points with timestamps less than or equal to this value. If not set, the time of the request is considered the endTime. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)</p>
         */
        _FinalStage endTime(Optional<String> endTime);

        _FinalStage endTime(String endTime);

        /**
         * <p>Set to true to enable feed mode for continuous reading updates. When enabled, the API always includes an endCursor in the response. If hasNextPage is false, it indicates that no new data is currently available — wait at least 5 seconds before making the next request to avoid unnecessary polling.</p>
         */
        _FinalStage feed(Optional<Boolean> feed);

        _FinalStage feed(Boolean feed);

        /**
         * <p>Optional boolean indicating whether to return external IDs on supported entities</p>
         */
        _FinalStage includeExternalIds(Optional<Boolean> includeExternalIds);

        _FinalStage includeExternalIds(Boolean includeExternalIds);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReadingIdStage, EntityTypeStage, _FinalStage {
        private String readingId;

        private String entityType;

        private Optional<Boolean> includeExternalIds = Optional.empty();

        private Optional<Boolean> feed = Optional.empty();

        private Optional<String> endTime = Optional.empty();

        private Optional<String> startTime = Optional.empty();

        private Optional<String> externalIds = Optional.empty();

        private Optional<String> entityIds = Optional.empty();

        private Optional<String> after = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetReadingsHistoryRequest other) {
            after(other.getAfter());
            readingId(other.getReadingId());
            entityIds(other.getEntityIds());
            entityType(other.getEntityType());
            externalIds(other.getExternalIds());
            startTime(other.getStartTime());
            endTime(other.getEndTime());
            feed(other.getFeed());
            includeExternalIds(other.getIncludeExternalIds());
            return this;
        }

        /**
         * <p>The reading ID to retrieve data for. Use /readings/definitions endpoint to get a list of valid reading IDs. (Examples: engineRpm,fuelLevel)</p>
         * <p>The reading ID to retrieve data for. Use /readings/definitions endpoint to get a list of valid reading IDs. (Examples: engineRpm,fuelLevel)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("readingId")
        public EntityTypeStage readingId(@NotNull String readingId) {
            this.readingId = Objects.requireNonNull(readingId, "readingId must not be null");
            return this;
        }

        /**
         * <p>A entity type of the entityIds or externalIds to fetch readings for. Use /readings/definitions endpoint to get a list of valid entity types. (Examples: asset, sensor)</p>
         * <p>A entity type of the entityIds or externalIds to fetch readings for. Use /readings/definitions endpoint to get a list of valid entity types. (Examples: asset, sensor)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("entityType")
        public _FinalStage entityType(@NotNull String entityType) {
            this.entityType = Objects.requireNonNull(entityType, "entityType must not be null");
            return this;
        }

        /**
         * <p>Optional boolean indicating whether to return external IDs on supported entities</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage includeExternalIds(Boolean includeExternalIds) {
            this.includeExternalIds = Optional.ofNullable(includeExternalIds);
            return this;
        }

        /**
         * <p>Optional boolean indicating whether to return external IDs on supported entities</p>
         */
        @java.lang.Override
        @JsonSetter(value = "includeExternalIds", nulls = Nulls.SKIP)
        public _FinalStage includeExternalIds(Optional<Boolean> includeExternalIds) {
            this.includeExternalIds = includeExternalIds;
            return this;
        }

        /**
         * <p>Set to true to enable feed mode for continuous reading updates. When enabled, the API always includes an endCursor in the response. If hasNextPage is false, it indicates that no new data is currently available — wait at least 5 seconds before making the next request to avoid unnecessary polling.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage feed(Boolean feed) {
            this.feed = Optional.ofNullable(feed);
            return this;
        }

        /**
         * <p>Set to true to enable feed mode for continuous reading updates. When enabled, the API always includes an endCursor in the response. If hasNextPage is false, it indicates that no new data is currently available — wait at least 5 seconds before making the next request to avoid unnecessary polling.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "feed", nulls = Nulls.SKIP)
        public _FinalStage feed(Optional<Boolean> feed) {
            this.feed = feed;
            return this;
        }

        /**
         * <p>A filter on the data that returns the last known data points with timestamps less than or equal to this value. If not set, the time of the request is considered the endTime. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage endTime(String endTime) {
            this.endTime = Optional.ofNullable(endTime);
            return this;
        }

        /**
         * <p>A filter on the data that returns the last known data points with timestamps less than or equal to this value. If not set, the time of the request is considered the endTime. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "endTime", nulls = Nulls.SKIP)
        public _FinalStage endTime(Optional<String> endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * <p>A filter on the data that returns the last known data points with timestamps greater than or equal to this value. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage startTime(String startTime) {
            this.startTime = Optional.ofNullable(startTime);
            return this;
        }

        /**
         * <p>A filter on the data that returns the last known data points with timestamps greater than or equal to this value. Must be a string in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2020-01-27T07:06:25Z)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "startTime", nulls = Nulls.SKIP)
        public _FinalStage startTime(Optional<String> startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * <p>A filter on the data based on this comma-separated list of external IDs. (Examples: samsara.serial:ZPXKLMN7VJ, samsara.serial:ABXKIMN4NM)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalIds(String externalIds) {
            this.externalIds = Optional.ofNullable(externalIds);
            return this;
        }

        /**
         * <p>A filter on the data based on this comma-separated list of external IDs. (Examples: samsara.serial:ZPXKLMN7VJ, samsara.serial:ABXKIMN4NM)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "externalIds", nulls = Nulls.SKIP)
        public _FinalStage externalIds(Optional<String> externalIds) {
            this.externalIds = externalIds;
            return this;
        }

        /**
         * <p>A filter on the data based on this comma-separated list of entity IDs or external IDs. If not set, all entities are returned.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage entityIds(String entityIds) {
            this.entityIds = Optional.ofNullable(entityIds);
            return this;
        }

        /**
         * <p>A filter on the data based on this comma-separated list of entity IDs or external IDs. If not set, all entities are returned.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "entityIds", nulls = Nulls.SKIP)
        public _FinalStage entityIds(Optional<String> entityIds) {
            this.entityIds = entityIds;
            return this;
        }

        /**
         * <p>If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage after(String after) {
            this.after = Optional.ofNullable(after);
            return this;
        }

        /**
         * <p>If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "after", nulls = Nulls.SKIP)
        public _FinalStage after(Optional<String> after) {
            this.after = after;
            return this;
        }

        @java.lang.Override
        public GetReadingsHistoryRequest build() {
            return new GetReadingsHistoryRequest(
                    after,
                    readingId,
                    entityIds,
                    entityType,
                    externalIds,
                    startTime,
                    endTime,
                    feed,
                    includeExternalIds,
                    additionalProperties);
        }
    }
}
