/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.samsara.api.resources.betaapis.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.samsara.api.core.ObjectMappers;
import com.samsara.api.resources.betaapis.types.TachographFileUploadsPostTachographFileUploadRequestBodyContentType;
import com.samsara.api.resources.betaapis.types.TachographFileUploadsPostTachographFileUploadRequestBodyFileType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TachographFileUploadsPostTachographFileUploadRequestBody.Builder.class)
public final class TachographFileUploadsPostTachographFileUploadRequestBody {
    private final String contentMd5;

    private final TachographFileUploadsPostTachographFileUploadRequestBodyContentType contentType;

    private final long fileSizeBytes;

    private final TachographFileUploadsPostTachographFileUploadRequestBodyFileType fileType;

    private final Map<String, Object> additionalProperties;

    private TachographFileUploadsPostTachographFileUploadRequestBody(
            String contentMd5,
            TachographFileUploadsPostTachographFileUploadRequestBodyContentType contentType,
            long fileSizeBytes,
            TachographFileUploadsPostTachographFileUploadRequestBodyFileType fileType,
            Map<String, Object> additionalProperties) {
        this.contentMd5 = contentMd5;
        this.contentType = contentType;
        this.fileSizeBytes = fileSizeBytes;
        this.fileType = fileType;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Base64-encoded MD5 digest of the file bytes (base64(md5(bytes))). Used as the Content-MD5 integrity check enforced by object storage on upload.
     */
    @JsonProperty("contentMd5")
    public String getContentMd5() {
        return contentMd5;
    }

    /**
     * @return The MIME content type of the file. The upload is sent to object storage as raw bytes.  Valid values: <code>application/octet-stream</code>
     */
    @JsonProperty("contentType")
    public TachographFileUploadsPostTachographFileUploadRequestBodyContentType getContentType() {
        return contentType;
    }

    /**
     * @return The size of the file in bytes. Enforced as the Content-Length on upload. Maximum 10 MB (10485760 bytes).
     */
    @JsonProperty("fileSizeBytes")
    public long getFileSizeBytes() {
        return fileSizeBytes;
    }

    /**
     * @return The kind of tachograph file being uploaded. The driver or device the file belongs to is resolved from the file contents, not from this field.  Valid values: <code>driverCard</code>, <code>vehicleUnit</code>
     */
    @JsonProperty("fileType")
    public TachographFileUploadsPostTachographFileUploadRequestBodyFileType getFileType() {
        return fileType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TachographFileUploadsPostTachographFileUploadRequestBody
                && equalTo((TachographFileUploadsPostTachographFileUploadRequestBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TachographFileUploadsPostTachographFileUploadRequestBody other) {
        return contentMd5.equals(other.contentMd5)
                && contentType.equals(other.contentType)
                && fileSizeBytes == other.fileSizeBytes
                && fileType.equals(other.fileType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.contentMd5, this.contentType, this.fileSizeBytes, this.fileType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ContentMd5Stage builder() {
        return new Builder();
    }

    public interface ContentMd5Stage {
        /**
         * <p>Base64-encoded MD5 digest of the file bytes (base64(md5(bytes))). Used as the Content-MD5 integrity check enforced by object storage on upload.</p>
         */
        ContentTypeStage contentMd5(@NotNull String contentMd5);

        Builder from(TachographFileUploadsPostTachographFileUploadRequestBody other);
    }

    public interface ContentTypeStage {
        /**
         * <p>The MIME content type of the file. The upload is sent to object storage as raw bytes.  Valid values: <code>application/octet-stream</code></p>
         */
        FileSizeBytesStage contentType(
                @NotNull TachographFileUploadsPostTachographFileUploadRequestBodyContentType contentType);
    }

    public interface FileSizeBytesStage {
        /**
         * <p>The size of the file in bytes. Enforced as the Content-Length on upload. Maximum 10 MB (10485760 bytes).</p>
         */
        FileTypeStage fileSizeBytes(long fileSizeBytes);
    }

    public interface FileTypeStage {
        /**
         * <p>The kind of tachograph file being uploaded. The driver or device the file belongs to is resolved from the file contents, not from this field.  Valid values: <code>driverCard</code>, <code>vehicleUnit</code></p>
         */
        _FinalStage fileType(@NotNull TachographFileUploadsPostTachographFileUploadRequestBodyFileType fileType);
    }

    public interface _FinalStage {
        TachographFileUploadsPostTachographFileUploadRequestBody build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ContentMd5Stage, ContentTypeStage, FileSizeBytesStage, FileTypeStage, _FinalStage {
        private String contentMd5;

        private TachographFileUploadsPostTachographFileUploadRequestBodyContentType contentType;

        private long fileSizeBytes;

        private TachographFileUploadsPostTachographFileUploadRequestBodyFileType fileType;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TachographFileUploadsPostTachographFileUploadRequestBody other) {
            contentMd5(other.getContentMd5());
            contentType(other.getContentType());
            fileSizeBytes(other.getFileSizeBytes());
            fileType(other.getFileType());
            return this;
        }

        /**
         * <p>Base64-encoded MD5 digest of the file bytes (base64(md5(bytes))). Used as the Content-MD5 integrity check enforced by object storage on upload.</p>
         * <p>Base64-encoded MD5 digest of the file bytes (base64(md5(bytes))). Used as the Content-MD5 integrity check enforced by object storage on upload.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("contentMd5")
        public ContentTypeStage contentMd5(@NotNull String contentMd5) {
            this.contentMd5 = Objects.requireNonNull(contentMd5, "contentMd5 must not be null");
            return this;
        }

        /**
         * <p>The MIME content type of the file. The upload is sent to object storage as raw bytes.  Valid values: <code>application/octet-stream</code></p>
         * <p>The MIME content type of the file. The upload is sent to object storage as raw bytes.  Valid values: <code>application/octet-stream</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("contentType")
        public FileSizeBytesStage contentType(
                @NotNull TachographFileUploadsPostTachographFileUploadRequestBodyContentType contentType) {
            this.contentType = Objects.requireNonNull(contentType, "contentType must not be null");
            return this;
        }

        /**
         * <p>The size of the file in bytes. Enforced as the Content-Length on upload. Maximum 10 MB (10485760 bytes).</p>
         * <p>The size of the file in bytes. Enforced as the Content-Length on upload. Maximum 10 MB (10485760 bytes).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fileSizeBytes")
        public FileTypeStage fileSizeBytes(long fileSizeBytes) {
            this.fileSizeBytes = fileSizeBytes;
            return this;
        }

        /**
         * <p>The kind of tachograph file being uploaded. The driver or device the file belongs to is resolved from the file contents, not from this field.  Valid values: <code>driverCard</code>, <code>vehicleUnit</code></p>
         * <p>The kind of tachograph file being uploaded. The driver or device the file belongs to is resolved from the file contents, not from this field.  Valid values: <code>driverCard</code>, <code>vehicleUnit</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fileType")
        public _FinalStage fileType(
                @NotNull TachographFileUploadsPostTachographFileUploadRequestBodyFileType fileType) {
            this.fileType = Objects.requireNonNull(fileType, "fileType must not be null");
            return this;
        }

        @java.lang.Override
        public TachographFileUploadsPostTachographFileUploadRequestBody build() {
            return new TachographFileUploadsPostTachographFileUploadRequestBody(
                    contentMd5, contentType, fileSizeBytes, fileType, additionalProperties);
        }
    }
}
